### ISSUE TITLE
Manager stuck at installing by non root method

### ISSUE THREAD

**Issue by harry590** [revanced/revanced-manager#160] opened 2022-09-17 11:01 UTC
When i patch the youtube, manager did all the patches but stuck on installing at the end even though youtube app has already been installed but still stuck on installing and also in patched applications list, youtube app wont appear.

How to fix this ?

**Comment by Aunali321** [comment] 2022-09-17 11:02
Dupe of #67

**Closed by Aunali321** 2022-09-17 11:02 UTC
