### ISSUE TITLE
Remove unused library 

### ISSUE THREAD

**Issue by monochrome11** [ReVanced/revanced-manager#1831] opened 2024-04-03 03:52 UTC
### Feature description

Add an option to remove unused library to save space by compile only arm64-v8a architecture.
![Screenshot_2024-04-03-09-17-03-81_d5ca8c38f86219f8d8dafdf022bf2e3b_1](https://github.com/ReVanced/revanced-manager/assets/71498159/8233be7f-b835-4014-a5d5-1dfa0a980e69)

### Motivation

To save some space.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by validcube** [comment] 2024-04-03 05:39
Duplicate of #1696

**Closed by validcube** 2024-04-03 05:39 UTC
Labels: Feature request
