### ISSUE TITLE
Provide Mirror Link

### ISSUE THREAD

**Issue by Mano5JP** [revanced/revanced-manager#495] opened 2022-11-09 12:57 UTC
### Type

Functionality

### Issue

Most of the time,  YouTube and music are updated with of play store versions. Sometimes we are unable to upgrade/downgrade to a recommended version . So, we must download from somewhere i.e. apkmirror.

### Feature

Add a button that will allow us to download the recommended apk file straight from apkmirror or other sources.

### Motivation

As it eliminates the lot of clicks/steps for the user to download an apk file, it would make things considerably faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2022-11-13 21:21
Dupe of #436, #125, #12

**Closed by Ushie** 2022-11-13 21:21 UTC
Labels: feature-request
