### ISSUE TITLE
bug: app not fully launching

### ISSUE THREAD

**Issue by MEGAtheguy** [revanced/revanced-manager#409] opened 2022-10-17 21:27 UTC
### Type

Error while running the manager

### Bug description

Unable to load main menus in app. Does not fully launch, only see boot/app logo

### Steps to reproduce

Tap app to open

### Android version

Android 13
TP1A.221005.002

### Manager version

0.0.34

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
Unable to reach
```

### Screenshots or videos

https://user-images.githubusercontent.com/12264494/196285961-17a005d5-7370-4b77-887c-575c299a88da.mp4

### Additional context

I have clean installed the app, made sure to clear data/cache where possible. Tried on and off VPN connection

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-18 06:26
Dupe of #379

**Closed by Aunali321** 2022-10-18 06:26 UTC
Labels: bug
