### ISSUE TITLE
Revanced manager still shows update available even on latest

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#805] opened 2023-04-21 07:14 UTC
### Type

Error at runtime

### Bug description

Revanced manager still shows update available even on latest version (0.1.1-dev.1)

### Steps to reproduce

1. Download and install version 0.1.1-dev.1
2. launch the application
3. Expect to see no updates available, instead it shows updates available
4. when clicked update, it shows version 0.1.0 even when the latest is 0.1.1
5. when installing the update via revanced manager, it rolled back to version 0.0.57

### Android version

13

### Manager version

0.1.1-dev.1

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Screenshots or videos

![Screenshot_2023-04-21-15-05-03-406_app revanced manager flutter-edit](https://user-images.githubusercontent.com/64138578/233565938-29b73f62-5d08-402b-9bbf-957698b573f2.jpg)

### Solution

Probably related to #802

### Additional context

There seems to be a few issues at play here.

1. The version labled 0.1.1-dev.1 on the release page actually conains version 0.1.0
2. The version code mismatch as stated in #802 
3. The update manager option showing the wrong version number to download (should be 0.1.1-dev.1 as it is the latest)
4. Mismatch between claimed downloaded file (0.1.0) and the downloaded file (0.0.57)
5. 0.0.57 has a higher version code than 0.1.0, therefore a old version can be installed over a new version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by SodaWithoutSparkles** [comment] 2023-04-21 07:16
Also, when I am absolutely sure that I insalled 0.1.1-dev.1, the about section of rv manager still said it is 0.1.0

```
Version: 0.1.0
Model: 22041216G
Android Version: 13
Arch: [arm64-v8a, armeabi-v7a, armeabi]
```

**Comment by psydvl** [comment] 2023-04-21 08:43
Caused by this commit https://github.com/revanced/revanced-manager/commit/109720c43bf794dbf4efe533a24221d0508cdfea

**Comment by SodaWithoutSparkles** [comment] 2023-04-21 09:50
WTF why `latest != current`? At least do `latest > current`.

Also a switch in settings for toggling between pre-release and stable version is probably a good idea.

**Comment by oSumAtrIX** [comment] 2023-04-21 12:49
@SodaWithoutSparkles You need to compare semantic versions such as 0.1.0 > 0.0.57

**Comment by oSumAtrIX** [comment] 2023-04-21 13:20
No, there is no overload for the `>` operator in statically typed languages for Strings.

**Comment by SodaWithoutSparkles** [comment] 2023-04-21 13:27
> No, there is no overload for the `>` operator in statically typed languages for Strings.

I am using python as pseudo-code here. Probably has something similar to `strcmp()` in C. Anyway, use this: https://stackoverflow.com/a/65077344

**Comment by arikyo07** [comment] 2023-04-29 18:03
The reason is simple. The version code of the released APK is 1.0.0, but the version returned by the API is v0.1.0. 
```json
{
  "tools": [
    {
      "repository": "revanced/revanced-manager",
      "version": "v0.1.0",
      "timestamp": "2023-04-29T17:08:17Z",
      "name": "revanced-manager-0.1.0.apk",
      "size": "57496665",
      "browser_download_url": "https://github.com/revanced/revanced-manager/releases/download/v0.1.0/revanced-manager-0.1.0.apk",
      "content_type": "application/vnd.android.package-archive"
    },
  ]
}
```

They changed the format of the pubspec version, but apparently forgot about it when they released it.
This can be fixed by simply renaming the release from v0.1.0 to v1.0.0.

**Comment by Ushie** [comment] 2023-04-29 18:05
It was an issue with the releases, as we're testing an automated release system

keep in mind all these releases say "-dev" in them, they're not meant to be used

**Closed by Ushie** 2023-04-29 18:05 UTC
Labels: bug

**Comment by prat89** [comment] 2023-05-01 05:07
+1

**Comment by Dhyfer1** [comment] 2023-05-01 20:45
Does anyone have the apk file for version 0.57.0? It was a big mistake that it was removed from releases. 😞
