### ISSUE TITLE
Can't install the recommended version of Revanced 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-manager#667] opened 2023-01-28 23:10 UTC
### Type

Error while running the manager

### Bug description

I can install YouTube revanced with YouTube version 17.49.37 normaly but can't install the recommended version 18.03.36, although it works normally as a YouTube app

### Steps to reproduce

Download version 18.03.36(no dpi)
Uninstall updates
Install version 18.03.36
Try to patch the app and you will get app not installed error 

### Android version

11

### Manager version

Latest version 0.0.53

### Target package name

YouTube app

### Target package version.

18.03.36

### Installation type

Non-root

### Patches selected.

Any

### Device logs (exported using Manager settings).

```shell
Logs are normal as if the app is successfuly installed
```

### Screenshots or videos

![Screenshot_2023-01-29-00-31-09-558_com google android packageinstaller](https://user-images.githubusercontent.com/120474122/215295257-c334615b-ceb0-4742-9924-2ece5d2cd581.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment] 2023-01-28 23:17
Dupe of https://github.com/revanced/revanced-patches/issues/1552 solved with https://github.com/revanced/revanced-patches/pull/1553.

**Closed by oSumAtrIX** 2023-01-28 23:17 UTC
Labels: bug

**Comment by michalani** [comment] 2023-02-03 22:37
+1 I am also experiencing this behaviour when updating via the package manager. My package manager version v0.0.54 which is one higher than the original reporter.

**Comment by EhabxAlaa** [comment] 2023-02-03 22:46
> +1 I am also experiencing this behaviour when updating via the package manager. My package manager version is v0.0.54 which is one higher than the original reporter.

Actually it was solved with patch v 2.158.0 and up, now i have no problem patching anything, make sure that you have everything updated to the latest version

**Comment by EhabxAlaa** [comment] 2023-02-03 22:47
> +1 I am also experiencing this behaviour when updating via the package manager. My package manager version is v0.0.54 which is one higher than the original reporter.

One other thing to sure of is that you don't have any downloaded YouTube revanced app before patching the new one
