### ISSUE TITLE
Update feature 

### ISSUE THREAD

**Issue by mnrsuristic** [revanced/revanced-manager#299] opened 2022-09-25 13:10 UTC
### Type

Functionality

### Issue

Well to keep it short I'm unable to update the Vanced manager app because I don't know if it's being updated ot not when I click "Update" 

### Feature

Adding a progress bar when clicking on "update" makes it easier to know when it starts and when it finishes updating, add a notification icon showing the progress bar so when I quit the app I can keep an ey on it

### Motivation

Boosting the overall user experience and making it better and easier to use

### Additional context

That's it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-09-25 13:16
Dupe of #239.

**Closed by Aunali321** 2022-09-25 13:16 UTC
Labels: feature-request
