### ISSUE TITLE
bug: can not install ReVanced Manager v0.0.25

### ISSUE THREAD

**Issue by prpjzz** [revanced/revanced-manager#307] opened 2022-09-26 03:58 UTC
### Type

Other

### Bug description

When I update ReVancred Manager with an available updater of the application or with an APK file on the Github of ReVancred Manager, the updater updates successfully, but when I check by entering the application information, the version of the application is 0.0.24 instead of 0.0.25

### Steps to reproduce

Step 1: Go to ReVanced Manager and Refresh Dashboard
Step 2: Update Manager → Yes and Wait
Step 3: Install → Update Sucessful

### Android version

9

### Manager version

v0.0.24

### Target package name

I haven't patched YouTube or YouTube Music yet.

### Target package version.

I haven't patched YouTube or YouTube Music yet.

### Installation type

Non-root

### Patches selected.

I haven't patched YouTube or YouTube Music yet.

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-26 10:19:38.939 19329 19329 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:27:29.160 21285 21285 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:27:55.772 22903 22903 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:28:14.034 23657 23657 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:28:30.797 24170 24170 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:29:40.077 24632 24632 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:30:25.285 25599 25599 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:30:31.984 25599 25599 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:30:38.713 26632 26632 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:41:10.137 27429 27429 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:41:36.238 28096 28096 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:43:06.498 29377 29377 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:43:25.850 29377 29377 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:43:31.788 29377 29377 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:44:05.171 29377 29377 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:44:39.998 30254 30254 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:44:41.034 30254 30254 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
09-26 10:46:28.790 30254 30254 V ActivityThread: handleTrimMemory:app.revanced.manager.flutter
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment] 2022-09-26 04:00
Dupe of https://github.com/revanced/revanced-manager/issues/306

**Closed by oSumAtrIX** 2022-09-26 04:00 UTC
Labels: bug
