### ISSUE TITLE
bug: kotlin.io.NoSuchFileException

### ISSUE THREAD

**Issue by FlyByKnight23** [ReVanced/revanced-manager#1034] opened 2023-07-17 06:17 UTC
### Type

Error while running the manager

### Bug description

This bug appears whenever I try to patch the recommended YT app

### Steps to reproduce

1. Download Revanced Manager.
2. Download the YouTube App from APKPure.
3. Patch Youtube

### Android version

13

### Manager version

1.4.1

### Target package name

com.google.android.youtube_18.23.35-1538252224_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk

### Target package version.

18.23.35

### Installation type

Non-root

### Patches selected.

Copy and pasted from exported .json

{"com.google.android.youtube":["Always autorepeat","Client spoof","Comments","Copy video url","Custom branding","Disable Shorts on startup","Disable auto captions","Disable fullscreen panels","Disable player popup panels","Disable zoom haptics","Enable debugging","External downloads","HDR auto brightness","Hide Shorts components","Hide ads","Hide album cards","Hide autoplay button","Hide breaking news shelf","Hide captions button","Hide cast button","Hide crowdfunding box","Hide email address","Hide endscreen cards","Hide filter bar","Hide floating microphone button","Hide info cards","Hide layout components","Hide load more button","Hide player buttons","Hide player overlay","Hide seekbar","Hide timestamp","Hide video action buttons","Hide watch in VR","Hide watermark","Minimized playback","Navigation buttons","Old video quality menu","Open links externally","Premium heading","Remember video quality","Return YouTube Dislike","Seekbar tapping","SponsorBlock","Spoof app version","Swipe controls","Tablet mini player","Theme","Vanced MicroG support","Video ads","Video speed","Wide searchbar"]}

### Device logs (exported using Manager settings).

```shell
the device log is too long and github won't let me post it
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborted
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: 6b648d00-2466-11ee-a3a8-89e4a871d196.bin does not exist
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:83)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:175)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or video

![Screenshot_20230717_021134](https://github.com/ReVanced/revanced-manager/assets/119979024/348c0d41-0e2d-4d17-abee-999ffecccbf7)

### Additional context

I followed all the instructions to the letter and it still isn't working

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-07-17 09:11
Duplicate of #975

**Closed by TheAabedKhan** 2023-07-17 09:11 UTC
Labels: bug
