### ISSUE TITLE
bug: patcher claims that original.apk source file doesn't exist when patching youtube despite it existing

### ISSUE THREAD

**Issue by BLucky-gh** [revanced/revanced-manager#1006] opened 2023-07-09 16:02 UTC
### Type

Error while running the manager

### Bug description

YouTube was annoying me with "uosate available" notifications so I downloaded the latest revanced recommended version from apkmirror and installed it fresh but when patching I an error that I pasted in the relevant logs section in this issue. Note that `original.apk` actually *does* exist at the path in the logs.

### Steps to reproduce

I'm not sure which of these steps are irrelevant but here's how I did it:
1. have a patched youtube installed already
2. get a newer version of the apk from apkmirror
3. install that apk to update youtube (and consequently unpatch it)
4. open revanced manager
5. choose youtube
6. try patching

### Android version

LineageOS 20
corresponds to android 13

### Manager version

1.3.8

### Target package name

youtube

### Target package version.

18.23.35

### Installation type

Root

### Patches selected.

The list is pretty long and the bug happens *before* the patches are even attempted, so I'll leave this empty and will send the patch list if it ends up being needed

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborted
Error:
kotlin.io.NoSuchFileException: /data/adb/revanced/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:114)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

https://github.com/revanced/revanced-patcher/assets/41377306/2f485b58-5e17-43b1-a39b-c08ed3cf227c

### Solution

pressing "Delete temporary files" in settings doesn't help, but using root to open `/data/adb/revanced/com.google.android.youtube/` and delete `base.apk` and `original.apk` with a file manager and then trying to patch again works.

### Additional context

https://discord.com/channels/952946952348270622/1127275480333168640

https://github.com/revanced/revanced-patcher/issues/205

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment] 2023-07-09 16:15
Duplicate of #975

**Closed by TheAabedKhan** 2023-07-09 16:15 UTC
Labels: bug
