### ISSUE TITLE
feat: Allow Manager to use dev branch for the patches

### ISSUE THREAD

**Issue by Domiiniik** [revanced/revanced-manager#829] opened 2023-04-29 16:13 UTC
### Type

Functionality

### Issue

Allow Manager to use dev branch for the patches

### Feature

~

### Motivation

Early Access patches testing

### Additional context

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2023-04-29 16:14
Duplicate of #821

**Closed by Ushie** 2023-04-29 16:14 UTC
Labels: feature-request
