### ISSUE TITLE
feat: Change patched app package id

### ISSUE THREAD

**Issue by GeekCornerGH** [revanced/revanced-manager#118] opened 2022-09-16 06:04 UTC
### Type

Other

### Branch

Flutter

### Issue

For now, if you patch an app which isn't YouTube or YT Music, then the package id will be the same as the original app.
I will use Reddit in this example :
So you patched Reddit, and patched works. That's fine, but since the package id is com.reddit.frontpage, you cann't update from play store without uninstalling patched app (or downloading apk, which leads to a bad UX).

### Feature

You should change package id to something like `app.revanced.reddit` to avoid updates issues

### Motivation

Because it improves UX and app updates flow.

**Comment by Aunali321** [comment] 2022-09-16 06:06
Duplicate of #108

**Closed by Aunali321** 2022-09-16 06:06 UTC
Labels: feature-request
