### ISSUE TITLE
bug:black screen on starup on fold 3(unoperable)<title>

### ISSUE THREAD

**Issue by omareg123** [revanced/revanced-manager#384] opened 2022-10-11 08:15 UTC
### Type

Other

### Bug description

I think the problem is in all foldable phones because of the ui. It may not that's my uneducated thought.

### Steps to reproduce

Install
Open
Black screen then nothing 

### Android version

Android 12, one ui 4.1

### Manager version

.30,.31
.29 works fine

### Target package name

Didn't open

### Target package version.

Didn't open 

### Installation type

Non-root

### Patches selected.

. 

### Device logs (exported using Manager settings).

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-11 08:23
Dupe of #379.

**Closed by Aunali321** 2022-10-11 08:23 UTC
Labels: bug

**Comment by omareg123** [comment] 2022-10-11 08:48
So I read the thread, I don't have adguard, I do have play services I've just updated YouTube from the play store. My phone isn't rooted or modified in any way
