### ISSUE TITLE
Removing Thumbnails embedded manually

### ISSUE THREAD

**Issue by Abish4i** [revanced/revanced-manager#585] opened 2022-12-13 11:36 UTC
### Type

Cosmetic

### Issue

Since google allowed manual uploading of thumbnails YouTube can be pretty nasty at showing clickbait more and more

### Feature

Request is for thumbnail removal tool which could be enabled as a patch to youtube.
There is an extension that hides thumbnail but What I'm requesting could not be mobile device still reaching out.

What if we Enable list view with no thumbnail or <s>autogenerated</s> thumbnail from server

### Motivation

Have used it on my PC could be a life saver from all those clickbaits that youtube recommends

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2022-12-13 11:41
Acknowledgements are not met, this issue is unrelated to ReVanced Manager, P.S. Dupe of revanced/revanced-patches#1208

**Closed by Ushie** 2022-12-13 11:41 UTC
Labels: feature-request
