### ISSUE TITLE
bug: Back buttons bugs

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#1510] opened 2023-11-21 20:54 UTC
### Bug description

**1 -** In both **Patched** and **Installed** screens the **manager's back** button doesn't work.

https://github.com/ReVanced/revanced-manager/assets/127908708/027821a3-ddc2-4867-b9f8-d7d880cac41f

https://github.com/ReVanced/revanced-manager/assets/127908708/a3596925-6b2e-4f36-a554-2af2c7738d3a

**2 -** In **Canceled** screen both the **manager's back** button and the **device's back** button don't work.

https://github.com/ReVanced/revanced-manager/assets/127908708/c589d8fb-14a8-4852-8a86-a6dce2455119

**3 -** In both **Patched** and **Installed** screens the **device's back** button makes you exit the manager instead of taking you to the manager's **Dashboard**.

https://github.com/ReVanced/revanced-manager/assets/127908708/a47ff23d-7cfe-4c26-8f24-68dd72dbc431

https://github.com/ReVanced/revanced-manager/assets/127908708/78122ce5-9836-4fc0-a55a-602be43c48ab

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.16.0

### Installation type

None

### Device logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment] 2023-12-09 10:23
This bug is a pretty annoying one as it causes the inconvenience of closing and reopening the manager whenever the user cancels patching, tries to patch and maybe wants to patch one app after the other.  
Previously a similar issue (#233 ) was when back button used to close the app instead of taking the user to dashboard.  But it was fixed with #1019.

**Comment by validcube** [comment] 2023-12-11 03:11
👋 Hi there, I have a strong feeling that this issue is caused by improvement to predictive back for Android 14 — https://github.com/ReVanced/revanced-manager/pull/1487 (whoops, that's my fault)

I'll revert this for now and reland (or reintroduce the feature) later once I fixed the issue.

**Comment by validcube** [comment] 2023-12-12 07:17
Try it now in manager v1.17.2 or higher!

**Comment by ILoveOpenSourceApplications** [comment] 2023-12-12 18:24
Yeah, looks like it's fixed now.

**Closed** 2023-12-12 18:41 UTC
Labels: bug
