### ISSUE TITLE
bug: Crash patching YouTube Music

### ISSUE THREAD

**Issue by pepoluan** [ReVanced/revanced-manager#1150] opened 2023-08-25 02:19 UTC
### Type

Error while running the manager

### Bug description

Manager 1.8.0 crashed trying to patch latest YouTube Music 6.15.51

### Steps to reproduce

1. Update Manager to latest
2. Install YouTube Music
3. Use manager to patch (apply all patches)
4. Crash

### Android version

12

### Manager version

1.8.0

### Target package name

YouTube Music

### Target package version.

6.15.51 (latest from Play Store as of 2023-08-25)

### Installation type

Non-root

### Patches selected.

All available (10 of them)

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
08-25 09:02:09.145 11217 11217 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
08-25 09:02:09.526 11217 11217 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.03
08-25 09:02:09.621 11217 11217 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=563ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=204ms seq=2 running=53ms runnable=42ms io=16ms binder=41ms late=7ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=357ms seq=3 running=68ms runnable=44ms io=19ms binder=120ms late=207ms h=android.app.ActivityThread$H w=159)
08-25 09:02:10.737 11217 11217 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=770ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=779ms seq=30 running=48ms runnable=6ms reclaim=2ms slowpath=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
08-25 09:02:58.441 17594 17594 I ForceDarkHelperStubImpl: initialize for app.revanced.manager.flutter , ForceDarkOrigin
08-25 09:02:58.642 17594 17594 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.03
08-25 09:02:58.697 17594 17594 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=348ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=139ms seq=2 running=51ms runnable=27ms io=19ms binder=28ms late=9ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=201ms seq=3 running=82ms runnable=39ms io=5ms binder=59ms late=147ms h=android.app.ActivityThread$H w=159)
08-25 09:02:59.646 17594 17594 W Looper  : PerfMonitor doFrame : time=35ms vsyncFrame=0 latency=906ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=909ms seq=8 running=51ms runnable=10ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
08-25 09:03:02.097 17594 17594 W Looper  : PerfMonitor longMsg : seq=48 plan=09:03:00.394 late=1ms wall=1700ms running=74ms runnable=22ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
08-25 09:03:36.179 17594 17594 W Activity: PerfMonitor: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onDestroy took 192ms
08-25 09:04:16.027 17594 17594 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=400ms procState=-1 historyMsgCount=2 (msgIndex=1 wall=401ms seq=308 running=36ms runnable=8ms late=24ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
--------- beginning of main
08-25 09:10:37.204 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:11:32.906 17594 17612 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:11:32.937 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xaae474a, mIsProjectionMode = false
08-25 09:11:32.937 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:11:32.937 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:11:32.937 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:11:32.957 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:11:32.961 17594 17954 I OpenGLRenderer: Davey! duration=122199ms; Flags=1, FrameTimelineVsyncId=12355720, IntendedVsync=389842441338666, Vsync=389842441338666, InputEventId=1062839719, HandleInputStart=389842443253365, AnimationStart=389842443254407, PerformTraversalsStart=389842443255032, DrawStart=389842469006647, FrameDeadline=389842474671998, FrameInterval=389842443238990, FrameStartTime=16666666, SyncQueued=389842469141699, SyncStart=389842469215345, IssueDrawCommandsStart=389842469332376, SwapBuffers=389842471099876, FrameCompleted=389964640595558, DequeueBufferDuration=1283750, QueueBufferDuration=306770, GpuCompleted=389964640595558, SwapBuffersCompleted=389842471594043, DisplayPresentTime=0, 
08-25 09:11:39.538 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:11:43.642 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:11:47.864 31349 31349 W sh      : type=1400 audit(0.0:175012): avc: denied { read } for name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c2,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-25 09:11:47.874 31349 31349 W sh      : type=1400 audit(0.0:175013): avc: denied { read } for name="/" dev="dm-5" ino=2 scontext=u:r:untrusted_app:s0:c2,c258,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-25 09:11:50.461 17594 17607 I manager.flutte: Background concurrent copying GC freed 1172824(43MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 149MB/173MB, paused 30us,62us total 160.293ms
08-25 09:11:50.979 17594 17607 I manager.flutte: Background concurrent copying GC freed 1613685(59MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 171MB/195MB, paused 29us,45us total 205.485ms
08-25 09:11:55.862 17594 17607 I manager.flutte: Background concurrent copying GC freed 3246551(95MB) AllocSpace objects, 9(11MB) LOS objects, 16% free, 117MB/141MB, paused 36us,21us total 140.948ms
08-25 09:11:55.863 17594 17609 W System  : A resource failed to call close. 
08-25 09:11:56.243 17594 17607 I manager.flutte: Background concurrent copying GC freed 3009142(64MB) AllocSpace objects, 2(132KB) LOS objects, 15% free, 129MB/153MB, paused 92us,19us total 196.925ms
08-25 09:11:56.597 17594 17607 I manager.flutte: Background concurrent copying GC freed 2373179(62MB) AllocSpace objects, 0(0B) LOS objects, 13% free, 153MB/177MB, paused 520us,20us total 162.311ms
08-25 09:11:57.112 17594 17607 I manager.flutte: Background concurrent copying GC freed 865120(25MB) AllocSpace objects, 4(496KB) LOS objects, 13% free, 154MB/178MB, paused 96us,76us total 141.989ms
08-25 09:11:57.524 17594 17607 I manager.flutte: Background concurrent copying GC freed 1579341(59MB) AllocSpace objects, 1(68KB) LOS objects, 12% free, 170MB/194MB, paused 67us,19us total 208.279ms
08-25 09:11:58.091 17594 17607 I manager.flutte: Background concurrent copying GC freed 1705768(63MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 189MB/213MB, paused 97us,19us total 246.089ms
08-25 09:12:02.740 17594 17607 I manager.flutte: Background concurrent copying GC freed 1628337(58MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 196MB/220MB, paused 40us,17us total 304.216ms
08-25 09:12:07.346 17594 17607 I manager.flutte: Background concurrent copying GC freed 3591289(114MB) AllocSpace objects, 15(10MB) LOS objects, 15% free, 131MB/155MB, paused 104us,19us total 145.493ms
08-25 09:12:07.346 17594 17609 W System  : A resource failed to call close. 
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6289: error: resource android:color/bright_foreground_dark_disabled is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6303: error: resource android:color/btn_default_material_dark is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6304: error: resource android:color/btn_leanback_color is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6305: error: resource android:color/bright_foreground_dark_inverse is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6306: error: resource android:color/btn_default_material_light is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6307: error: resource android:color/btn_leanback_focused is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6308: error: resource android:color/background_floating_device_default_light is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6309: error: resource android:color/background_device_default_light is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6310: error: resource android:color/car_action1 is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6311: error: resource android:color/car_action1_dark is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6312: error: resource android:color/background_holo_light is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6313: error: resource android:color/background_floating_material_light is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6314: error: resource android:color/car_blue_100 is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6315: error: resource android:color/car_blue_200 is private.
08-25 09:12:15.014 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6316: error: resource android:color/bright_foreground_disabled_holo_light is private.
08-25 09:12:15.015 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6317: error: resource android:color/accent_device_default_700 is private.
08-25 09:12:15.015 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6318: error: resource android:color/btn_colored_borderless_text_material is private.
08-25 09:12:15.015 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6319: error: resource android:color/bright_foreground_dark is private.
08-25 09:12:15.015 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6320: error: resource android:color/background_material_dark is private.
08-25 09:12:15.015 17594 31716 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/res/values/styles.xml:6321: error: resource android:color/car_blue_50 is private.
08-25 09:12:21.984 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:12:22.264 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:12:24.492 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:12:32.942 17594 17594 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#9](f:0,a:2) Applying pending transactions on dtor 1
08-25 09:12:38.733 17594 17954 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:12:38.775 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xd05b794, mIsProjectionMode = false
08-25 09:12:38.775 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:12:38.775 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:12:38.775 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:12:38.785 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:12:38.789 17594 18001 I OpenGLRenderer: Davey! duration=126005ms; Flags=1, FrameTimelineVsyncId=12360211, IntendedVsync=389904466669004, Vsync=389904483335670, InputEventId=868813761, HandleInputStart=389904488600894, AnimationStart=389904488602248, PerformTraversalsStart=389904488602873, DrawStart=389904508333133, FrameDeadline=389904500002336, FrameInterval=389904488557665, FrameStartTime=16666666, SyncQueued=389904508972613, SyncStart=389904509138967, IssueDrawCommandsStart=389904509272873, SwapBuffers=389904511974227, FrameCompleted=390030472081471, DequeueBufferDuration=2030781, QueueBufferDuration=615677, GpuCompleted=390030472081471, SwapBuffersCompleted=389904513076467, DisplayPresentTime=0, 
08-25 09:12:42.176 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:14:33.380 17594 17612 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:14:33.416 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xc40a0d7, mIsProjectionMode = false
08-25 09:14:33.416 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:33.416 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:33.416 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:33.435 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:14:33.450 17594 18001 I OpenGLRenderer: Davey! duration=180501ms; Flags=1, FrameTimelineVsyncId=12365907, IntendedVsync=389964613291809, Vsync=389964613291809, InputEventId=0, HandleInputStart=389964614245610, AnimationStart=389964614246496, PerformTraversalsStart=389964614247017, DrawStart=389964629960663, FrameDeadline=389964646625141, FrameInterval=389964614210819, FrameStartTime=16666666, SyncQueued=389964632991913, SyncStart=389964633162538, IssueDrawCommandsStart=389964633278475, SwapBuffers=389964639810090, FrameCompleted=390145114708771, DequeueBufferDuration=5875365, QueueBufferDuration=486927, GpuCompleted=390145114708771, SwapBuffersCompleted=389964640872485, DisplayPresentTime=0, 
08-25 09:14:35.614 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:14:48.545 17594 18001 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:14:48.580 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xd956dc7, mIsProjectionMode = false
08-25 09:14:48.580 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:48.580 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:48.580 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:14:48.593 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:14:48.595 17594 18001 I OpenGLRenderer: Davey! duration=129834ms; Flags=1, FrameTimelineVsyncId=12369213, IntendedVsync=390030441851284, Vsync=390030441851284, InputEventId=416061285, HandleInputStart=390030442252044, AnimationStart=390030442252721, PerformTraversalsStart=390030442253346, DrawStart=390030467460012, FrameDeadline=390030475184616, FrameInterval=390030442235533, FrameStartTime=16666666, SyncQueued=390030467907773, SyncStart=390030468072512, IssueDrawCommandsStart=390030468191731, SwapBuffers=390030470980273, FrameCompleted=390160276939286, DequeueBufferDuration=1277552, QueueBufferDuration=740729, GpuCompleted=390160276939286, SwapBuffersCompleted=390030472206992, DisplayPresentTime=0, 
08-25 09:14:52.433 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:15:22.091 17594 17612 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:15:22.107 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xbbdd9b6, mIsProjectionMode = false
08-25 09:15:22.107 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:15:22.107 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:15:22.107 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:15:22.121 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:15:22.135 17594 17954 I OpenGLRenderer: Davey! duration=163361ms; Flags=1, FrameTimelineVsyncId=12369213, IntendedVsync=390030441851284, Vsync=390030441851284, InputEventId=416061285, HandleInputStart=390030442252044, AnimationStart=390030442252721, PerformTraversalsStart=390030442253346, DrawStart=390030467460012, FrameDeadline=390030491851282, FrameInterval=390030442235533, FrameStartTime=16666666, SyncQueued=390030467907773, SyncStart=390030468072512, IssueDrawCommandsStart=390030468191731, SwapBuffers=390030470980273, FrameCompleted=390193803904898, DequeueBufferDuration=1277552, QueueBufferDuration=740729, GpuCompleted=390193803904898, SwapBuffersCompleted=390030472206992, DisplayPresentTime=0, 
08-25 09:15:24.122 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:17:09.079 17594 17612 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:17:09.110 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x94e1c66, mIsProjectionMode = false
08-25 09:17:09.110 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:09.111 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:09.111 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:09.123 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-25 09:17:09.136 17594 18001 I OpenGLRenderer: Davey! duration=155717ms; Flags=1, FrameTimelineVsyncId=12379725, IntendedVsync=390145092014719, Vsync=390145092014719, InputEventId=0, HandleInputStart=390145092291896, AnimationStart=390145092292469, PerformTraversalsStart=390145092292990, DrawStart=390145108541687, FrameDeadline=390145125348051, FrameInterval=390145092241115, FrameStartTime=16666666, SyncQueued=390145109139396, SyncStart=390145109284760, IssueDrawCommandsStart=390145110358458, SwapBuffers=390145112484760, FrameCompleted=390300809438295, DequeueBufferDuration=1053959, QueueBufferDuration=564844, GpuCompleted=390300809438295, SwapBuffersCompleted=390145113944448, DisplayPresentTime=0, 
08-25 09:17:19.079 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-25 09:17:24.095 17594 17954 D AppScoutStateMachine: 17594-ScoutStateMachinecreated
08-25 09:17:24.099 17594 17594 I InstallPlugin: handleActivityResult(2,0,null)
08-25 09:17:24.148 17594 17594 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xc144b33, mIsProjectionMode = false
08-25 09:17:24.148 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:24.148 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:24.148 17594 17594 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
08-25 09:17:24.162 17594 17954 I OpenGLRenderer: Davey! duration=155595ms; Flags=1, FrameTimelineVsyncId=12381357, IntendedVsync=390160246594092, Vsync=390160246594092, InputEventId=51555543, HandleInputStart=390160247014234, AnimationStart=390160247014963, PerformTraversalsStart=390160247015588, DrawStart=390160273314338, FrameDeadline=390160279927424, FrameInterval=390160246995900, FrameStartTime=16666666, SyncQueued=390160273861369, SyncStart=390160274032098, IssueDrawCommandsStart=390160274150015, SwapBuffers=390160276257567, FrameCompleted=390315842467768, DequeueBufferDuration=1335052, QueueBufferDuration=521823, GpuCompleted=390315842467768, SwapBuffersCompleted=390160277297515, DisplayPresentTime=0, 
08-25 09:17:24.177 17594 17594 D DecorView[]: onWindowFocusChanged hasWindowFocus true
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Compact header
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~bmRkFulu0wFYblXUckTXeA==/app.revanced.manager.flutter-UOJcjQnwwgY4qjcaJnp1Ug==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61551240, --version-name, 6.15.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2734426193260409750.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~bmRkFulu0wFYblXUckTXeA==/app.revanced.manager.flutter-UOJcjQnwwgY4qjcaJnp1Ug==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61551240, --version-name, 6.15.51, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2734426193260409750.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNHVIT/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by KobeW50** [comment] 2023-08-25 02:34
Use version 6.10.52 until this is fixed

**Comment by TheAabedKhan** [comment] 2023-08-25 06:43
Duplicate of #1130

**Closed by TheAabedKhan** 2023-08-25 06:43 UTC
Labels: bug

**Comment by pepoluan** [comment] 2023-08-25 18:14
> Use version 6.10.52 until this is fixed

Thanks!

The manager should probably be updated to say that as well. Currently it just effectively says "install any version of YouTube Music"
