### ISSUE TITLE
bug: PatchOptionException$InvalidValueTypeException

### ISSUE THREAD

**Issue by User132New** [ReVanced/revanced-manager#2278] opened 2024-11-01 00:50 UTC
### Bug description

Bug while patching Google Photos app : An error occurred:
app.revanced.patcher.patch.options.PatchOptionException$InvalidValueTypeException

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.22.0
Google Photos[revanced-manager_logcat_20241101061801198798.log](https://github.com/user-attachments/files/17594601/revanced-manager_logcat_20241101061801198798.log)

### Installation method

Regular

### ReVanced Manager logs

An error occurred:
app.revanced.patcher.patch.options.PatchOptionException$InvalidValueTypeException

### Patch logs

- Device Info
ReVanced Manager: 1.22.0
Model: Redmi Note 10S
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.1.0.677535587 (Suggested: Any)
Patches version: v4.17.0
Patches added: Default
Patches removed: None
Default patch options changed: Spoof features [Features to enable: [com.google.android.apps.photos.NEXUS_PRELOAD, com.google.android.apps.photos.nexus_preload], Features to disable: [com.google.android.apps.photos.PIXEL_2017_PRELOAD, com.google.android.apps.photos.PIXEL_2018_PRELOAD, com.google.android.apps.photos.PIXEL_2019_MIDYEAR_PRELOAD, com.google.android.apps.photos.PIXEL_2019_PRELOAD, com.google.android.feature.PIXEL_2020_MIDYEAR_EXPERIENCE, com.google.android.feature.PIXEL_2020_EXPERIENCE, com.google.android.feature.PIXEL_2021_MIDYEAR_EXPERIENCE, com.google.android.feature.PIXEL_2021_EXPERIENCE, com.google.android.feature.PIXEL_2022_MIDYEAR_EXPERIENCE, com.google.android.feature.PIXEL_2022_EXPERIENCE, com.google.android.feature.PIXEL_2023_MIDYEAR_EXPERIENCE, com.google.android.feature.PIXEL_2023_EXPERIENCE, com.google.android.feature.PIXEL_2024_MIDYEAR_EXPERIENCE, com.google.android.feature.PIXEL_2024_EXPERIENCE, com.google.android.feature.PIXEL_2025_MIDYEAR_EXPERIENCE]]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
An error occurred:
app.revanced.patcher.patch.options.PatchOptionException$InvalidValueTypeException: Type [Ljava.lang.String; was expected but received type java.util.ArrayList
	at app.revanced.patcher.patch.options.PatchOptions.set(Unknown Source:58)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:411)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-LAAAIA/out.apk' (OS Error: No such file or directory, errno = 2)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by cycalo** [comment] 2024-11-01 21:16
Same issue here and with a few other apps like SoundCloud

**Comment by dickta** [comment] 2024-11-10 05:40
I have the same issue.

- Device Info
ReVanced Manager: 1.22.0
Model: M2012K11AG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.7.0.694530673 (Suggested: Any)
Patches version: v4.17.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tROWnLJu3MWTbFmk1Be_tA==/app.revanced.manager.flutter-BBP3mOvAPeqqZW5tDJY6mw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-SPADGO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-SPADGO/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~tROWnLJu3MWTbFmk1Be_tA==/app.revanced.manager.flutter-BBP3mOvAPeqqZW5tDJY6mw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-SPADGO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-SPADGO/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-SPADGO/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by oSumAtrIX** [comment] 2024-12-07 20:06
Should be fixed.

**Closed by oSumAtrIX** 2024-12-07 20:06 UTC
Labels: Bug report
