### ISSUE TITLE
bug: output apk doesn't exist

### ISSUE THREAD

**Issue by sssh7710** [ReVanced/revanced-manager#1084] opened 2023-08-04 08:03 UTC
### Type

Error while running the manager

### Bug description

Attempted to export post-patch apps except for non-functional patches

### Steps to reproduce

1. Patched the app as Manager
2. Select App Export
3. Specify a location and export
4. App bounces and files in storage location 0B

### Android version

android 13,one 5.1

### Manager version

1.6.1

### Target package name

youtube

### Target package version.

18.23.25

### Installation type

Non-root

### Patches selected.

Select all except change package key option

### Device logs (exported using Manager settings).

```shell
....
```

### Screenshots or video

![Screenshot_20230804_170019_My Files](https://github.com/ReVanced/revanced-manager/assets/98168192/1a056ce4-65b2-4819-a5cc-27d63d7c7172)

### Additional context

Strangely enough, the tablet works fine
[revanced-manager_logcat_20230804165441486273.log](https://github.com/ReVanced/revanced-manager/files/12258537/revanced-manager_logcat_20230804165441486273.log)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-08-04 08:07
Can you please provide a screen recording reproducing this issue?

**Comment by sssh7710** [comment] 2023-08-04 08:16
> 이 문제를 재현하는 화면 녹화를 제공할 수 있습니까?

Just a moment, please.

**Comment by griffi-gh** [comment] 2023-08-04 08:21
i have the same issue, rvm always produces a 0b file

**Comment by sssh7710** [comment] 2023-08-04 08:32
All of a sudden, this error doesn't occur now

**Comment by TheAabedKhan** [comment] 2023-08-04 09:01
> All of a sudden, this error doesn't occur now

OK.

@griffi-gh can you provide a screen recording please?

**Comment by Ushie** [comment] 2023-08-04 12:11
@TheAabedKhan I have a screenrecording and a log from last night regarding this issue

https://github.com/ReVanced/revanced-manager/assets/79272171/dfd389a2-d24e-4d7a-9ab4-dafc0e4d8650

```08-03 23:43:21.720  9690  9690 E AndroidRuntime: FATAL EXCEPTION: main
--
2 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 9690
3 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-PSBJDQ/out.apk: open failed: ENOENT (No such file or directory)
4 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.IoBridge.open(IoBridge.java:574)
5 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at java.io.FileInputStream.
6 | <init>(FileInputStream.java:160)
7 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
8 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
9 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
13 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
14 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
15 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.Linux.open(Native Method)
16 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
17 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
18 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
19 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:9209)
20 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     at libcore.io.IoBridge.open(IoBridge.java:560)
21 | 08-03 23:43:21.720  9690  9690 E AndroidRuntime:     ... 8 more
22 | 08-03 23:51:54.754 21520 21520 E AndroidRuntime: FATAL EXCEPTION: main
23 | 08-03 23:51:54.754 21520 21520 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 21520
24 | 08-03 23:51:54.754 21520 21520 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNHOMH/out.apk: open failed: ENOENT (No such file or directory)
25 | 08-03 23:51:54.754 21520 21520 E AndroidRuntime:     at libcore.io.IoBridge.open(IoBridge.java:574)
26 | 08-03 23:51:54.754 21520 21520 E AndroidRuntime:     at java.io.FileInputStream.
27 | <init>(FileInputStream.java:160)```

**Comment by TheAabedKhan** [comment] 2023-08-04 12:19
@Ushie Looks like this issue is happening with non-rooted devices only. Working on a fix

**Comment by oSumAtrIX** [comment] 2023-08-28 00:37
Should be fixed

**Closed by oSumAtrIX** 2023-08-28 00:37 UTC
Labels: bug
