### ISSUE TITLE
Crash after allowing install from unknown sources 

### ISSUE THREAD

**Issue by tashilapathum** [ReVanced/revanced-manager#633] opened 2023-01-07 13:14 UTC
### Type

Error at runtime

### Bug description

Crashes when coming back to the app after allowing install from unknown sources 

### Steps to reproduce

1. Install app
2. Open for the first time
3. 'Install apps from unknown sources' page automatically opens
4. Allow
5. Press back and go to Vanced Manager
6. Crash

### Android version

11

### Manager version

0.0.52

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
Logs weren't exporting for some reason so Here's the stack trace from device:

`java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4552)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4584)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5146)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4539)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
	at android.app.Activity.dispatchActivityResult(Activity.java:8531)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5139)
	... 12 more
`
```

### Additional context

Model: Redmi Note 8
Arch: arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-12 17:23
Is this another one of MIUI related bugs or was this related to the manager?

**Comment by Palocay** [comment] 2023-02-13 08:50
I excluded some of the patches I added recently (Predictive Back Gesture, Spoof App Version, Spoof Wifi Connection) and patched it again with v17.49.37. This seems to work, the patched app doesn't crash anymore. I'll try version 18.03.36 in a minute, but it seems that these or one of these patches isn't supported.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-13 12:04
Closing this for now as it's not due to manager probably.

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-25 18:31
@oSumAtrIX is this actually an issue related to the manager? This or #713 ?

**Comment by oSumAtrIX** [comment] 2023-02-25 18:42
I cant reproduce this issue, btw @ILoveOpenSourceApplications mark issues with the "question" label so you can come back to them after time passes, if you leave a question on an issue

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-25 19:12
Okay, will do that in the future.

**Comment by ILoveOpenSourceApplications** [comment] 2023-07-20 20:07
Since this issue is months old and no further clarification is given I'm closing this issue. Feel free to comment if it exists still.

**Closed by ILoveOpenSourceApplications** 2023-07-20 20:07 UTC
Labels: bug, question
