### ISSUE TITLE
bug: back gesture does not work properly

### ISSUE THREAD

**Issue by kidonng** [ReVanced/revanced-manager#1158] opened 2023-08-27 08:18 UTC
### Type

Other

### Bug description

System-wide back gesture does not work properly, rather it returns to the launcher or last application.

This issue does not exist on 1.8.0.

### Steps to reproduce

1. Open manager
2. Open any sub-view (e.g. app info)
3. Perform back gesture
4. Returned to last application rather than last view

### Android version

13 (MIUI 14.0.7)

### Manager version

1.9.3

### Target package name

N/A

### Target package version.

N/A

### Installation type

Root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A (please correct me if this is necessary)
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/44045911/9a9f18ae-7a6f-45df-b374-63509d7ff992

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by jr1221** [comment] 2023-08-27 13:19
Present in v1.9.0

**Comment by ego-lay-atman-bay** [comment] 2023-08-27 13:45
I can also confirm that this happens on my non-rooted device. Oh, and I'm using the 3-button navigation, so the back button doesn't work as well (it's not just the gesture).

**Comment by nightznero** [comment] 2023-08-28 04:59
v1.9.4 still presents the same issue,nothing changed in this case yet

**Comment by validcube** [comment] 2023-09-03 14:28
This is quite odd, I couldn't see a commit that cause the back gesture to not work properly.

I'll look into it!

**Comment by validcube** [comment] 2023-09-03 15:01
Looks like this issue is caused by Flutter, someone has already reported the issue at flutter/flutter 117061

**Comment by Ushie** [comment] 2023-09-03 15:01
Depends on https://github.com/flutter/flutter/issues/117061

**Comment by jr1221** [comment] 2023-09-03 15:03
Yup.  I bisected it and failed now I know why.

**Comment by Ushie** [comment] 2023-09-04 04:44
Turns out I can't read, it's https://github.com/flutter/flutter/issues/132476

Fix will be in v1.9.6

**Closed** 2023-09-04 05:17 UTC
Labels: bug
