### ISSUE TITLE
bug: Revanced Manager hard-crashes while patching Youtube with many (~45) patches

### ISSUE THREAD

**Issue by bigyihsuan** [revanced/revanced-manager#567] opened 2022-12-08 18:05 UTC
### Type

Error while running the manager

### Bug description

I am trying to patch Youtube with many patches, and midway through the patching process, Revanced Manager hard crashes.

### Steps to reproduce

1. Install Youtube v17.45.36 and Revanced Manager v0.0.44.
2. Select all the patches available for Youtube.
3. Attempt to patch Youtube.
4. Revanced Manager will hard-crash while patching.

### Android version

Android 11 (Oxygen OS 11.0.6.1.GM57AA)

### Manager version

0.0.44

### Target package name

com.google.android.youtube

### Target package version.

v17.45.36

### Installation type

Non-root

### Patches selected.

All patches available.

### Device logs (exported using Manager settings).

(log is too long, here is a gist link: https://gist.github.com/bigyihsuan/ecf8d2eb8430028a96119d74f2cea074)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by anoraktrend** [comment] 2022-12-14 13:38
Possible dupe of:  #268

**Comment by ILoveOpenSourceAppications** [comment] 2023-02-11 17:48
Selecting all patches is not recommended at all even. Why would you select all the patches in the first place?

**Comment by oSumAtrIX** [comment] 2023-02-11 17:49
It is merely unrecommended, not particularly wrong.

**Closed by oSumAtrIX** 2023-02-11 17:49 UTC
Labels: bug
