### ISSUE TITLE
System language

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-manager#531] opened 2022-11-24 06:17 UTC
### Type

Functionality

### Issue

Automatic adaptation of the ReVanced Manager application's language selection to the system language. No need to change application language anymore. But we can change it again if we want.

### Feature

ReVanced Manager uses the device's system language without a key.

### Motivation

Because this feature is available in Vanced Manager or almost all applications.

### Additional context

There is no.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by CennoxX** [comment] 2022-11-24 08:43
Duplicate of #243

**Closed** 2022-11-28 17:15 UTC
Labels: Feature request
