### ISSUE TITLE
feat: Show patches release notes

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [ReVanced/revanced-manager#1539] opened 2023-11-30 17:55 UTC
### Feature description

In the dashboard, if you tap on patches, it'll show the release notes of the current version. This could be the same for the manager section as well.

### Motivation

What if there's a bugfix that doesn't update the recommended version? That doesn't make is obvious that I need to update my apps. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment] 2023-11-30 18:31
Duplicate of https://github.com/ReVanced/revanced-manager/issues/1413

**Comment by ego-lay-atman-bay** [comment] 2023-11-30 18:34
Yeah, but I would like to see the release notes after updating.

**Comment by ego-lay-atman-bay** [comment] 2023-12-12 23:26
So... I had turned off auto update patches for a while, but just today, it updated the patches in the background without telling me, even though I turned off auto update. Now, this was before I updated the manager, so I don't know if this was fixed already.

**Closed** 2024-03-05 00:48 UTC
Labels: Feature request
