### ISSUE TITLE
Revanced manager can't repatch already patched app

### ISSUE THREAD

**Issue by some1onLSD** [ReVanced/revanced-manager#1027] opened 2023-07-15 15:26 UTC
### Type

Error at runtime

### Bug description

I wans trying to update/change youtube patches when some new patches were out. but the installer said that "/data/adb/revanced/original.apk" doesn't exist, I have root so I checked and it does exist.

### Steps to reproduce

1- Patch Youtube with any patch using revanced manager.
2- Try to update youtube patches when a new patches are out.
3- The installer says that "/data/adb/revanced/original.apk" doesn't exist, I have root so I checked and it does exist.

### Android version

13

### Manager version

v1.4.0

### Target package name

Youtube

### Target package version.

Any

### Installation type

Root

### Patches selected.

Any

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
07-15 16:19:51.356 23478 23478 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
07-15 16:19:51.444 23478 23478 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10181; state: ENABLED
07-15 16:19:51.599 23478 23478 V GraphicsEnvironment: ANGLE Developer option for 'app.rvx.manager.flutter' set to: 'default'
07-15 16:19:51.599 23478 23478 V GraphicsEnvironment: ANGLE GameManagerService for app.rvx.manager.flutter: false
07-15 16:19:51.599 23478 23478 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-15 16:19:51.603 23478 23478 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-15 16:19:51.603 23478 23478 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-15 16:19:51.774 23478 23478 W manager.flutter: type=1400 audit(0.0:62541): avc: denied { read } for name="max_map_count" dev="proc" ino=206216 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.rvx.manager.flutter
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: QUALCOMM build                   : 8e5405b, I57aaec3440
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: Build Date                       : 05/21/21
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.10
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: Local Branch                     : mybranchebba1dbe-451b-f160-ac81-1458d0b52ae8
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r135-rel
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: Remote Branch                    : NONE
07-15 16:19:51.808 23478 23478 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
07-15 16:19:51.809 23478 23478 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
07-15 16:19:51.809 23478 23478 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-15 16:19:51.817 23478 23478 I AdrenoGLES-0: PFP: 0x016ee187, ME: 0x00000000
07-15 16:19:52.046 23478 26505 E OpenGLRenderer: Unable to match the desired swap behavior.
07-15 16:19:52.094 26524 26524 W sh      : type=1400 audit(0.0:62542): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:19:52.124 26524 26524 W sh      : type=1400 audit(0.0:62543): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:19:52.144 26524 26524 W sh      : type=1400 audit(0.0:62544): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:19:52.174 26524 26524 W sh      : type=1400 audit(0.0:62545): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:19:54.291 23478 26510 I flutter : dynamic_color: Core palette detected.
07-15 16:19:54.484 23478 26511 I Gralloc4: mapper 4.x is not supported
07-15 16:19:54.485 23478 26511 W Gralloc3: mapper 3.x is not supported
07-15 16:19:54.491 23478 26511 W Gralloc4: allocator 4.x is not supported
07-15 16:19:54.496 23478 26511 W Gralloc3: allocator 3.x is not supported
07-15 16:19:54.499 23478 26511 I Gralloc2: Adding additional valid usage bits: 0x8202000
07-15 16:19:54.595 23478 26511 E BLASTBufferQueue: [SurfaceView[app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2340, requested_size=1080x2340 buffer{size=1080x2214 transform=0}
07-15 16:19:54.600 23478 23478 E SurfaceSyncer: Failed to find sync for id=0
07-15 16:19:54.600 23478 23478 E SurfaceSyncer: Failed to find sync for id=1
07-15 16:19:54.622 23478 26505 W Parcel  : Expecting binder but got null!
07-15 16:20:03.894 26524 26524 W sh      : type=1400 audit(0.0:62550): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:03.934 26524 26524 W sh      : type=1400 audit(0.0:62551): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:03.954 26524 26524 W sh      : type=1400 audit(0.0:62552): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:03.994 26524 26524 W sh      : type=1400 audit(0.0:62553): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:04.024 26524 26524 W sh      : type=1400 audit(0.0:62554): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:05.924 26524 26524 W sh      : type=1400 audit(0.0:62558): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:05.954 26524 26524 W sh      : type=1400 audit(0.0:62559): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:05.984 26524 26524 W sh      : type=1400 audit(0.0:62560): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:06.014 26524 26524 W sh      : type=1400 audit(0.0:62561): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:06.044 26524 26524 W sh      : type=1400 audit(0.0:62562): avc: denied { read } for name="/" dev="mmcblk0p58" ino=2 scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
07-15 16:20:14.067 23478 26498 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
07-15 16:20:14.064 23478 23478 W FinalizerDaemon: type=1400 audit(0.0:62566): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c181,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=app.rvx.manager.flutter
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborted
Error:
kotlin.io.NoSuchFileException: /data/adb/revanced/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:114)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Solution

reinstall youtube

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-07-15 16:33
Did you unpatch the app before applying the new patches?

**Comment by some1onLSD** [comment] 2023-07-20 19:52
tried it both ways and it won't patch anywya

**Comment by TheAabedKhan** [comment] 2023-07-21 02:54
So, this issue can be considered as the duplicate of #975

**Closed by TheAabedKhan** 2023-07-21 02:54 UTC
Labels: bug
