### ISSUE TITLE
bug: ReVanced doesn't start after non-root install

### ISSUE THREAD

**Issue by johan-perso** [revanced/revanced-manager#195] opened 2022-09-18 10:37 UTC
### Type

Error at runtime

### Branch

Flutter, I think

### Bug description

I installed ReVanced from the manager, and the app just don't start (crash instantly, or show a grey empty background then crash after few minutes)

### Steps to reproduce

1. Patch YouTube
2. Install as non-root
3. Start the app

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20220918-122309](https://user-images.githubusercontent.com/41506568/190897833-2dc54105-6c78-446b-b347-d94d9e5a28cc.png)
![Screenshot_20220918-122859](https://user-images.githubusercontent.com/41506568/190897840-d60569e1-0429-479f-872e-65c9b523a0a9.png)
![Screenshot_20220918-122902](https://user-images.githubusercontent.com/41506568/190897841-0165d032-7845-44d8-b95e-544f63c2d174.png)

### Additional context

Version: 0.0.13
Model: Pixel 6a
Android Version: 13
Arch: arm64-v8a

**Comment by Alprnn357** [comment] 2022-09-18 10:43
You have included MicroG Support. So you have to install microg services eg. [Vanced Microg](https://github.com/TeamVanced/VancedMicroG/releases)

**Comment by AndryOut** [comment] 2022-09-18 10:44
I had problems with version 17.36.37, gray screen or crash. Then out of curiosity I tried to use the version 17.33.42 And it worked properly without any problems

**Comment by pietryszak** [comment] 2022-09-18 10:50
> I had problems with version 17.36.37, gray screen or crash. Then out of curiosity I tried to use the version 17.33.42 And it worked properly without any problems 

Did you download full app from APK mirror 17.36?

**Comment by AndryOut** [comment] 2022-09-18 10:54
> > I had problems with version 17.36.37, gray screen or crash. Then out of curiosity I tried to use the version 17.33.42 And it worked properly without any problems
> 
> Did you download full app from APK mirror 17.36?

I downloaded the app from Mirror apk, then I tried version 17.33.42 and it works (manager 0.0.13)

**Comment by pietryszak** [comment] 2022-09-18 10:56
> > > I had problems with version 17.36.37, gray screen or crash. Then out of curiosity I tried to use the version 17.33.42 And it worked properly without any problems
> > 
> > Did you download full app from APK mirror 17.36?
> 
> I downloaded the app from Mirror apk, then I tried version 17.33.42 and it works (manager 0.0.13) 

I have same problem but with 17.33, when i download 17.36 works fine with 0.0.13

**Comment by johan-perso** [comment] 2022-09-18 10:57
> @johan-perso Did you download full app from APK mirror 17.36?

YouTube is preinstalled on my phone i can't really use a apk to reinstall it, maybe with adb??

**Comment by johan-perso** [comment] 2022-09-18 11:11
I managed to uninstall YouTube using adb, 17.36 doesn't work but 17.33.42 looks fine

**Comment by pietryszak** [comment] 2022-09-18 11:20
> I managed to uninstall YouTube using adb, 17.36 doesn't work but 17.33.42 looks fine
> Keeping this issue open as some of the latest versions don't seem to work

Yes it's work. I check that on my Android 12. 0.0.13 and 17.36 works fine

**Comment by Aunali321** [comment] 2022-09-18 12:00
Exclude hdr patch.

**Comment by pietryszak** [comment] 2022-09-18 12:03
> Exclude hdr patch.

@Aunali321 You have very bad approach to closing issues. Stop closing issues without confirmation that a solution working, from end user.

**Comment by Aunali321** [comment] 2022-09-18 12:11
I understand but 80% of the issues here are duplicate. And i reopen issues when solution doesn't work.

**Comment by pietryszak** [comment] 2022-09-18 12:16
> I understand but 80% of the issues here are duplicate. And i reopen issues when solution doesn't work.

I understund, but this is a Alpha stage, so I think dev needs confirmation that provided solution, realy works as expected. 
Approuch to close a issue, without confirmation can be better on beta/stable stage when a dev was 100% shure that solution works.

**Comment by Aunali321** [comment] 2022-09-18 12:17
Sure, will do better next time.

**Comment by OscarDL** [comment] 2022-09-18 12:39
> Exclude hdr patch.

Thanks for reopening the issue, because I'm having this app not starting issue as well and I haven't installed the hdr patch, so this isn't it. I installed the bare minimum of patches and this still won't open, so the app version being the issue is more plausible I'm guessing.


https://user-images.githubusercontent.com/27915933/190902490-5f3213ef-d482-4d4e-b603-7c001fd5f2a3.mp4

**Comment by pietryszak** [comment] 2022-09-18 12:43
> e as well and I haven't installed the hdr patch, so this isn't it. I installed the bare minimum of patches and this still won't open, so the app version being the issue is more plausible I'

Did you install gmicro ?

**Comment by theuserwhoisnotadeveloper** [comment] 2022-09-18 13:30
> I managed to uninstall YouTube using adb, 17.36 doesn't work but 17.33.42 looks fine Keeping this issue open as some of the latest versions don't seem to work

use [Universal Android Debloater](https://github.com/0x192/Universal-Android-Debloater) when you need to remove system apps without root. it is much easier.

**Comment by OscarDL** [comment] 2022-09-18 13:32
> Did you install gmicro vanced edition? Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases)

I indeed had not installed it, just did and tried again, but still hangs on app startup. One of the logs I could read says `java.security.AccessControlException: Access not allowed for non-Google app: app.revanced.android.youtube`, couldn't find anything more useful unfortunately, but doesn't seem like it's microG or the HDR patch causing this issue and probably still the version number.

**Comment by johan-perso** [comment] 2022-09-18 13:32
> > I managed to uninstall YouTube using adb, 17.36 doesn't work but 17.33.42 looks fine Keeping this issue open as some of the latest versions don't seem to work
> 
> use [Universal Android Debloater](https://github.com/0x192/Universal-Android-Debloater) when you need to remove system apps without root. it is much easier.

Seems useful, will try the next time I need

**Comment by Doalou** [comment] 2022-09-18 13:34
I have the same problem !

**Comment by johan-perso** [comment] 2022-09-18 13:35
> I understand but 80% of the issues here are duplicate. And i reopen issues when solution doesn't work.

I tried installing Vanced with only the Client Spoof patch, it didn't work neither

Only method was to downgrade my original YouTube

**Comment by Aunali321** [comment] 2022-09-18 13:37
Please try with yt 17.33.42. make sure it's full apk.

**Comment by pietryszak** [comment] 2022-09-18 13:39
> > I understand but 80% of the issues here are duplicate. And i reopen issues when solution doesn't work.
> 
> I tried installing Vanced with only the Client Spoof patch, it didn't work neither
> 
> Only method was to downgrade my original YouTube

Let's tell me how i install.
1) Download newest manager
2) Download 17.36 full apk from apk mirror
3) Download gmicro vanced edition
4) Install microg
5) Uninstall all updates from original youtube app from google play
6) Install full apk 17.36. Not open it
7) Install manager
8) Patch 17.36
9) Install patched 17.36
10) Disable original youtube app
11) Open new Yt vanced app

**Comment by johan-perso** [comment] 2022-09-18 13:47
> Please try with yt 17.33.42. make sure it's full apk.

That's the version I use, and it works nice.
The twitter patch also needed to downgrade btw

**Comment by trmdi** [comment] 2022-09-19 05:05
> Exclude hdr patch.

Doesn't help.

**Comment by Yjuser1** [comment] 2022-09-19 05:11
How to set refresh on the home page，
mine cannot be refreshed

**Comment by Aunali321** [comment] 2022-09-19 05:20
Please send logs from manager.

**Comment by ponces** [comment] 2022-09-19 11:32
Problem solved.
Closed.

**Closed** 2022-09-19 11:32 UTC
Labels: bug
