### ISSUE TITLE
feat: add languages in app, and make manager use android default language

### ISSUE THREAD

**Issue by KiGamji** [ReVanced/revanced-manager#243] opened 2022-09-20 12:32 UTC
### Type

Functionality

### Manager Branch

Flutter

### Issue

Currently, there is only english language available in app, no more languages available yet. Hence, no android default language detection and auto selection present.

### Feature

Add languages support, and make manager use selected android language by default.

P.S. It would be a great idea to add integral value percentage of translated strings of every language in future language selection menu. A way to implement that, can be comparing ? language strings with en.json. If they're the same (unedited and in english), then count that as not translated string.

### Motivation

Not anyone in the world knows english, ig there is so many people, who don't understand english, hence they pretty much can't use the manager or ask for help with it in revanced social media.

**Comment by CennoxX** [comment] 2022-11-10 16:32
Possible duplicate of  #17

**Closed** 2023-08-05 17:51 UTC
Labels: feature-request

**Comment by KiGamji** [comment] 2025-06-27 10:01
nice
