### ISSUE TITLE
Original apk dosent exits 

### ISSUE THREAD

**Issue by Mediumx** [ReVanced/revanced-manager#1028] opened 2023-07-15 17:03 UTC
### Type

Error while running the manager

### Bug description

wont let me patch

### Steps to reproduce

normal steps

### Android version

13

### Manager version

latest

### Target package name

Youtube

### Target package version.

recommended

### Installation type

Root

### Patches selected.

![image](https://github.com/ReVanced/revanced-manager/assets/139644540/7a556ba5-61b9-45af-8f64-f3013bc78912)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborted
Error:
kotlin.io.NoSuchFileException: /data/adb/revanced/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:114)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-07-15 18:54
If you are freshly patching the app, then your issue is a duplicate of #975.
If your are patching already patched app, then your issue is a duplicate of #1027.

**Closed by TheAabedKhan** 2023-07-15 18:54 UTC
Labels: bug
