### ISSUE TITLE
Custom apk can't be selected.

### ISSUE THREAD

**Issue by HybridShivam** [revanced/revanced-manager#142] opened 2022-09-16 18:40 UTC
### Type

Error while running the manager

### Branch

flutter

### Bug description

Storage apk selection does nothing.

### Steps to reproduce

1. Install `manager`
2. select `patcher`
4. select `storage`
5. select custom `youtube.apk`
6. nothing happens(no application selected)

### Relevant log output

```shell
none
```

**Comment by turbo4door** [comment] 2022-09-16 23:59
I'm having the same issue with trying to patch the Twitter APK. Select the APK from storage and then nothing happens.

**Comment by Aunali321** [comment] 2022-09-17 06:08
Duplicate of #93.

**Closed by Aunali321** 2022-09-17 06:08 UTC
Labels: bug
