### ISSUE TITLE
Youtube music while repacking getting aborted

### ISSUE THREAD

**Issue by harry590** [ReVanced/revanced-manager#1143] opened 2023-08-20 16:07 UTC
### Type

Error while running the manager

### Bug description

When i try to update or newly patch yt music then during repacking stage the process gets aborted in version 6.13.52 and latest one 6.15.51.

### Steps to reproduce

After installing the patches while repacking apk it happens

### Android version

Android 13

### Manager version

1.8.0

### Target package name

Youtube music

### Target package version.

6.13.52 and 6.15.51

### Installation type

Non-root

### Patches selected.

Default ones

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
08-20 20:17:12.652 30576 30576 E AndroidRuntime: FATAL EXCEPTION: main
08-20 20:17:12.652 30576 30576 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 30576
08-20 20:17:12.652 30576 30576 E AndroidRuntime: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GJKNNJ/out.apk: open failed: ENOENT (No such file or directory)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.IoBridge.open(IoBridge.java:574)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at java.io.FileInputStream.<init>(FileInputStream.java:160)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at com.cleveroad.cr_file_saver.utils.FileKt$saveFileInBackground$1$file$1.invokeSuspend(File.kt:71)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-20 20:17:12.652 30576 30576 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.Linux.open(Native Method)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8619)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   at libcore.io.IoBridge.open(IoBridge.java:560)
08-20 20:17:12.652 30576 30576 E AndroidRuntime:   ... 8 more
--------- beginning of main
08-20 20:39:17.045  2010  2039 D OpenGLRenderer: setSurface called with nullptr
08-20 20:40:57.670  2010  2010 I ViewRootImpl@1a33fed[MainActivity]: handleAppVisibility mAppVisible = false visible = true
08-20 20:40:57.671  2010  2010 I ViewRootImpl@1a33fed[MainActivity]: stopped(false) old = true
08-20 20:40:57.671  2010  2010 I ViewRootImpl@1a33fed[MainActivity]: WindowStopped on app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity set to false
08-20 20:40:57.689  2010  2010 D SurfaceView@4e03472: updateSurface: surface is not valid
08-20 20:40:57.689  2010  2010 I SurfaceView@4e03472: releaseSurfaces: viewRoot = ViewRootImpl@1a33fed[MainActivity]
08-20 20:40:57.697  2010  2010 I SurfaceView@4e03472: applyTransactionOnVriDraw: vri = ViewRootImpl@1a33fed[MainActivity] fRS = true t = 0xb4000076e5dec590 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setVisibility:392 
08-20 20:40:57.697  2010  2010 I SurfaceView@4e03472: applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
08-20 20:40:57.697  2010  2010 I ViewRootImpl@1a33fed[MainActivity]: applyTransactionOnDraw: mRemoved = false isHardwareEnabled = false t = 0xb4000076e5dec590android.view.ViewRootImpl.applyTransactionOnDrawFromReleaseSurfaces:12850 android.view.SurfaceView.applyTransactionOnVriDraw:2046 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setVisibility:392 
08-20 20:40:57.703  2010  2010 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@a906458[MainActivity]
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/bqJReHNceHKf5wE3rTDq1Q==/app.revanced.manager.flutter-v_AmRxm6t1SzRtXajQUpSw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2017502169404825405.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/build/resources.zip]
  at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
  at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
  at app.revanced.patcher.Patcher.save(Patcher.kt:128)
  at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
  at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
  at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
  at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/bqJReHNceHKf5wE3rTDq1Q==/app.revanced.manager.flutter-v_AmRxm6t1SzRtXajQUpSw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2017502169404825405.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JLPEKP/cache/build/resources.zip]
  at brut.util.OS.exec(OS.java:99)
  at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
  ... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-08-20 17:18
Duplicate of #988 and use YouTube Music v6.10.52

**Closed by TheAabedKhan** 2023-08-20 17:18 UTC
Labels: bug
