### ISSUE TITLE
bug: Revanced Manager

### ISSUE THREAD

**Issue by dark-caster** [revanced/revanced-manager#235] opened 2022-09-20 03:10 UTC
### Type

Other

### Manager Branch

Flutter

### Bug description

I'd like to report a bug I found in Revanced Manager. After finishing the compilation, when you click on the "Share APK" button, the Android share menu appears (so far so good).

But, if you close Android share menu, and **click "Share APK" button a second time, it doesn't work**. It is necessary to redo the compilation to share a second time. **The "Share APK" button only works once.**

The same bug occurs with the "Share log" button.

### Steps to reproduce

**Press "Share APK" button once**: Android share menu appears normally.

**If you close the share menu** (by clicking on an app to upload or simply pressing the "back" button), **the "Share APK" button no longer works**.

**Need to close the Revanced Manager and redo the whole process again** (choose the app, the patches and do the compilation) **to use the "Share APK" button, but it still only works once.**

The same bug occurs with the "Share log" button.

### Android version

Android 8.1.0 Oreo
Android 10
Android 12

### Manager version

0.0.13
0.0.14

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
09-20 00:03:50.637  4435  4435 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-20 00:03:50.640  4435  4435 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-20 00:03:50.653  4435  4435 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10668; state: ENABLED
09-20 00:03:50.798  4435  4435 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-20 00:03:50.798  4435  4435 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-20 00:03:50.798  4435  4435 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-20 00:03:50.799  4435  4435 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-20 00:03:50.918  4435  4435 W manager.flutter: type=1400 audit(0.0:31479): avc: denied { read } for name="max_map_count" dev="proc" ino=5489093 scontext=u:r:untrusted_app:s0:c156,c258,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: QUALCOMM build                   : 5eaa426211, I07ee46fc66
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Build Date                       : 10/08/21
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Local Branch                     : 
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Remote Branch                    : 
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Remote Branch                    : 
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Reconstruct Branch               : 
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-20 00:03:50.930  4435  4435 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-20 00:03:50.936  4435  4435 I AdrenoGLES-0: PFP: 0x016ee197, ME: 0x00000000
09-20 00:03:51.070  4435  4460 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-20 00:03:52.469  4435  4465 I flutter : dynamic_color: Core palette detected.
09-20 00:03:52.655  4435  4435 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 00:03:52.655  4435  4435 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 00:03:52.655  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 00:03:52.655  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 00:03:52.655  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 00:03:52.655  4435  4435 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 00:03:52.655  4435  4435 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 00:03:52.655  4435  4435 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
09-20 00:03:52.655  4435  4435 W System.err: 	at android.os.Looper.loop(Looper.java:329)
09-20 00:03:52.655  4435  4435 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8058)
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 00:03:52.655  4435  4435 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
09-20 00:03:52.655  4435  4435 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 00:03:52.655  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 00:03:52.655  4435  4435 W System.err: 	... 19 more
09-20 00:03:52.667  4435  4520 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-20 00:03:52.667  4435  4520 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-20 00:03:52.748  4435  4465 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_regular_d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf'
09-20 00:03:52.822  4435  4465 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_500_ec3a64e46e2ee5f546845582e1d5409107780cef55bc43b052ee962f9807aee6.ttf'
09-20 00:03:52.840  4435  4435 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-20 00:03:52.840  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 00:03:52.840  4435  4435 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 00:03:52.840  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 00:03:52.840  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 00:03:52.840  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 00:03:52.840  4435  4435 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 00:03:52.840  4435  4435 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 00:03:52.840  4435  4435 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
09-20 00:03:52.840  4435  4435 W System.err: 	at android.os.Looper.loop(Looper.java:329)
09-20 00:03:52.840  4435  4435 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8058)
09-20 00:03:52.840  4435  4435 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 00:03:52.840  4435  4435 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
09-20 00:03:52.841  4435  4435 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-20 00:03:52.841  4435  4435 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 00:03:52.841  4435  4435 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 00:03:52.841  4435  4435 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 00:03:52.841  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 00:03:52.841  4435  4435 W System.err: 	... 19 more
09-20 00:03:53.079  4435  4465 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Inter_regular_ca30a452e6f1961d934a7c782130cbcba3bbb9b611aae1dac1279d396350b35e.ttf'
09-20 00:03:53.154  4435  4520 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-20 00:03:53.154  4435  4520 W SQLiteLog: (28) double-quoted string literal: "584833A27CF9B773B0A84CEF2A337694"
09-20 00:03:53.776  4435  4520 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-20 00:03:53.776  4435  4520 W SQLiteLog: (28) double-quoted string literal: "BE00820C7ED8D980B4A41D0D625579D0"
09-20 00:03:56.467  4435  4435 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-20 00:03:56.468  4435  4435 D FilePickerDelegate: Selected type */*
09-20 00:03:56.985  4435  4435 E BLASTBufferQueue: [ViewRootImpl[MainActivity]#0](f:0,a:1) Applying pending transactions on dtor 1
09-20 00:03:58.704  4435  4920 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/08D8-10EF%3ADownload%2Fcom.google.android.youtube_17.36.37-1531571648_minAPI26(arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64)(nodpi)_apkmirror.com.apk
09-20 00:03:58.767  4435  4613 I OpenGLRenderer: Davey! duration=5972ms; Flags=1, FrameTimelineVsyncId=2896624, IntendedVsync=89341647903947, Vsync=89341647903947, InputEventId=0, HandleInputStart=89341648855929, AnimationStart=89341648857804, PerformTraversalsStart=89341648859366, DrawStart=89341649398325, FrameDeadline=89341681237279, FrameInterval=89341648852804, FrameStartTime=16666666, SyncQueued=89341649835043, SyncStart=89341649944366, IssueDrawCommandsStart=89341651979210, SwapBuffers=89341668352649, FrameCompleted=89347620320430, DequeueBufferDuration=1245469, QueueBufferDuration=627761, GpuCompleted=89347620320430, SwapBuffersCompleted=89341669816087, DisplayPresentTime=0, 
09-20 00:04:02.495  4435  4920 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_17.36.37-1531571648_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
09-20 00:04:02.496  4435  4920 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@67aa680]
09-20 00:04:05.134  4435  4435 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-20 00:04:05.136  4435  4435 D FilePickerDelegate: Selected type */*
09-20 00:04:07.755  4435  4435 I FilePickerDelegate: User cancelled the picker request
09-20 00:04:07.822  4435  4613 I OpenGLRenderer: Davey! duration=15022ms; Flags=1, FrameTimelineVsyncId=2896624, IntendedVsync=89341647903947, Vsync=89341647903947, InputEventId=0, HandleInputStart=89341648855929, AnimationStart=89341648857804, PerformTraversalsStart=89341648859366, DrawStart=89341649398325, FrameDeadline=89341697903945, FrameInterval=89341648852804, FrameStartTime=16666666, SyncQueued=89341649835043, SyncStart=89341649944366, IssueDrawCommandsStart=89341651979210, SwapBuffers=89341668352649, FrameCompleted=89356671010081, DequeueBufferDuration=1245469, QueueBufferDuration=627761, GpuCompleted=89356671010081, SwapBuffersCompleted=89341669816087, DisplayPresentTime=0, 
09-20 00:04:14.594  4435  4444 W manager.flutte: Cleared Reference was only reachable from finalizer (only reported once)
09-20 00:04:14.623  4435  4449 W System  : A resource failed to call close. 
09-20 00:04:14.623  4435  4449 W System  : A resource failed to call close. 
09-20 00:06:04.807  4435  4465 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/JetBrainsMono_regular_7d41ab308fc765375a9977c24f462964f639e89b8447ac6b149e93dc0e3e7b1c.ttf'
09-20 00:06:05.055  4435  4435 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10668; state: ENABLED
09-20 00:06:08.458  4435  4435 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-20 00:06:08.458  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 00:06:08.458  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 00:06:08.458  4435  4435 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 00:06:08.458  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 00:06:08.458  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 00:06:08.458  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 00:06:08.458  4435  4435 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 00:06:08.458  4435  4435 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 00:06:08.458  4435  4435 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
09-20 00:06:08.458  4435  4435 W System.err: 	at android.os.Looper.loop(Looper.java:329)
09-20 00:06:08.458  4435  4435 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8058)
09-20 00:06:08.458  4435  4435 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 00:06:08.459  4435  4435 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 00:06:08.459  4435  4435 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
09-20 00:06:08.459  4435  4435 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-20 00:06:08.459  4435  4435 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 00:06:08.459  4435  4435 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 00:06:08.459  4435  4435 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 00:06:08.459  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 00:06:08.459  4435  4435 W System.err: 	... 19 more
09-20 00:06:08.470  4435  4435 W ziparchive: Unable to open '/data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/2b3943e0-3891-11ed-b17a-ad13187a2fde.dm': No such file or directory
09-20 00:06:10.982  4435  4444 I manager.flutte: Background concurrent copying GC freed 152039(5294KB) AllocSpace objects, 1(24KB) LOS objects, 44% free, 29MB/53MB, paused 49us,51us total 105.697ms
09-20 00:06:13.567  4435  4444 I manager.flutte: Background concurrent copying GC freed 498662(17MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 61MB/85MB, paused 53us,31us total 301.393ms
09-20 00:06:15.509  4435  4444 I manager.flutte: Background concurrent copying GC freed 542433(21MB) AllocSpace objects, 6(9048KB) LOS objects, 21% free, 87MB/111MB, paused 49us,62us total 393.766ms
09-20 00:06:28.053  4435  4444 I manager.flutte: Background concurrent copying GC freed 852857(29MB) AllocSpace objects, 0(0B) LOS objects, 16% free, 125MB/149MB, paused 58us,25us total 643.840ms
09-20 00:06:41.984  4435  4444 I manager.flutte: Background concurrent copying GC freed 546386(25MB) AllocSpace objects, 18(10MB) LOS objects, 17% free, 111MB/135MB, paused 62us,28us total 597.678ms
09-20 00:06:57.431  4435  4444 I manager.flutte: Background concurrent copying GC freed 413551(14MB) AllocSpace objects, 6(296KB) LOS objects, 14% free, 144MB/168MB, paused 71us,35us total 525.771ms
09-20 00:07:19.585  4435  4444 I manager.flutte: Background young concurrent copying GC freed 552516(13MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 161MB/164MB, paused 62us,31us total 101.663ms
09-20 00:07:20.478  4435  4449 W System  : A resource failed to call close. 
09-20 00:08:19.629  4435  4444 I manager.flutte: Background concurrent copying GC freed 1422(39MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 60MB/84MB, paused 322us,27us total 109.801ms
09-20 00:08:22.358  4435  5371 I flutter : dynamic_color: Core palette detected.
09-20 00:08:22.428  4435  4435 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 00:08:22.429  4435  4435 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 00:08:22.429  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 00:08:22.429  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 00:08:22.429  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 00:08:22.429  4435  4435 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 00:08:22.429  4435  4435 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 00:08:22.429  4435  4435 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
09-20 00:08:22.429  4435  4435 W System.err: 	at android.os.Looper.loop(Looper.java:329)
09-20 00:08:22.429  4435  4435 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8058)
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 00:08:22.429  4435  4435 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
09-20 00:08:22.429  4435  4435 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 00:08:22.429  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 00:08:22.429  4435  4435 W System.err: 	... 19 more
09-20 00:08:22.467  4435  4435 W System.err: java.io.IOException: Cannot run program "su": error=2, No such file or directory
09-20 00:08:22.467  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-20 00:08:22.467  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-20 00:08:22.467  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-20 00:08:22.469  4435  4435 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-20 00:08:22.469  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-20 00:08:22.469  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-20 00:08:22.469  4435  4435 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-20 00:08:22.469  4435  4435 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
09-20 00:08:22.469  4435  4435 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-20 00:08:22.469  4435  4435 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
09-20 00:08:22.469  4435  4435 W System.err: 	at android.os.Looper.loop(Looper.java:329)
09-20 00:08:22.469  4435  4435 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8058)
09-20 00:08:22.469  4435  4435 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-20 00:08:22.469  4435  4435 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
09-20 00:08:22.470  4435  4435 W System.err: Caused by: java.io.IOException: error=2, No such file or directory
09-20 00:08:22.470  4435  4435 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-20 00:08:22.470  4435  4435 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-20 00:08:22.470  4435  4435 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-20 00:08:22.470  4435  4435 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-20 00:08:22.470  4435  4435 W System.err: 	... 19 more
```

**Comment by Aunali321** [comment] 2022-09-20 03:28
Can you reproduce on 0.0.16?

**Comment by devlocalhost** [comment] 2022-09-20 18:52
> Can you reproduce on 0.0.16?

I can't. Android 13 qpr1 beta 1 GSI

**Comment by ponces** [comment] 2022-09-22 11:50
It was fixed some time ago. If user can't reproduce it anymore I think we should close this.
Agree @Aunali321 ?

**Comment by Aunali321** [comment] 2022-09-22 11:52
I think this is fixed. Closing.

**Closed by Aunali321** 2022-09-22 11:52 UTC
Labels: bug
