### ISSUE TITLE
bug: <title> Black screen 

### ISSUE THREAD

**Issue by Hermxy** [revanced/revanced-manager#400] opened 2022-10-16 08:50 UTC
### Type

Other

### Bug description

After version 29 it gives a black screen.  My Phone galaxy j7 prime2

### Steps to reproduce

![Screenshot_20221016-104603](https://user-images.githubusercontent.com/115921484/196026726-071902f2-ab42-4d63-8ce5-e0576a45d0a9.jpg)

### Android version

Android 9

### Manager version

Versiyon 0.32

### Target package name

Non

### Target package version.

Non

### Installation type

Root

### Patches selected.

Non

### Device logs (exported using Manager settings).

```shell
Non
```

### Screenshots or videos

![Screenshot_20221016-104603](https://user-images.githubusercontent.com/115921484/196026845-122a37cd-976b-41b2-ba8d-92d260fa49bc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-16 09:42
Dupe of #379.

**Closed by Aunali321** 2022-10-16 09:42 UTC
Labels: bug
