### ISSUE TITLE
bug: tiktok

### ISSUE THREAD

**Issue by bodua233** [ReVanced/revanced-manager#1595] opened 2023-12-25 11:01 UTC
### Bug description

Bug

### Version of ReVanced Manager and version & name of application you tried to patch

- Patch Info
App: com.ss.android.ugc.trill v32.5.3 (Suggested: v32.5.3)
Patches version: v3.1.0
Patches added: Default
Patches removed: None
Default patch options changed: None

### Installation type

None

### Device logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: RMX3370
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: RMX3370
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.ss.android.ugc.trill v32.5.3 (Suggested: v32.5.3)
Patches version: v3.1.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 8325648 byte allocation with 7393552 free bytes and 7220KB until OOM, target footprint 536870912, growth limit 536870912
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:256)
	at com.google.common.io.ByteStreamsHack.toByteArray(ByteStreamsHack.java:30)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:55)
	at lanchon.multidexlib2.ZipFileDexContainer.<init>(ZipFileDexContainer.java:48)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:62)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:48)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:39)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:33)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:43)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:41)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at app.revanced.patcher.data.BytecodeContext.getClasses(BytecodeContext.kt:41)
	at app.revanced.patcher.data.BytecodeContext$Integrations.flush(BytecodeContext.kt:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:189)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment] 2023-12-25 11:06
👋 Hi, unfortunately, either your phone doesn't have the at least 2 GB of memory or there's an issue which is related to #1454

I am marking this as a duplicate for now.

**Comment by validcube** [comment] 2023-12-25 11:06
duplicate of #1454

**Closed by validcube** 2023-12-25 11:06 UTC
Labels: bug
