### ISSUE TITLE
Option to download latest/versions supported Youtube Apks from verified sources

### ISSUE THREAD

**Issue by vaishnavmhetre** [revanced/revanced-manager#132] opened 2022-09-16 15:30 UTC
### Type

Functionality

### Branch

main

### Issue

Currently we need to install YouTube/Music from Play Store or alternate sources for old versions, but need to fiddle around finding the right version for right patches+/integrations. 

### Feature

It would be cool if we integrate way to download YouTube/Music apk with version comparison to current patches+integrations and list those patches+integrations as listed description when downloading the YouTube/Music from our app. 

In case it becomes a compliance argumentative issue like Vanced, we could provide link to the source of download instead of direct download to device, now making user responsible for the actions ( _I have least knowledge for this, so choice lies with you_ 😬)

### Motivation

**Tbh its a case of ease of access so users could get running with modded Ytb/music in a breeze.** 

Maybe when others read this request, they could add more to this section of what they feel.

**Comment by Aunali321** [comment] 2022-09-16 15:43
Duplicate of #125.

**Closed by Aunali321** 2022-09-16 15:43 UTC
Labels: feature-request

**Comment by vaishnavmhetre** [comment] 2022-09-16 17:13
But I created with proper template 😔
