### ISSUE TITLE
bug: Revanced Manager 0.0.30+ will not start

### ISSUE THREAD

**Issue by ThePillarist** [revanced/revanced-manager#388] opened 2022-10-11 20:37 UTC
### Type

Error at runtime

### Bug description

When loading any version after 0.0.29 the splash screen shows and the app goes no further. Android 13 on Pixel 6 Pro. 

### Steps to reproduce

Attempt to run app.

### Android version

13 Build No.:T1B2.220916.004

### Manager version

0.0.31

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-11 20:39
Dupe of #379. also fixed in latest version. should be released in ~10 mins.

**Closed by Aunali321** 2022-10-11 20:39 UTC
Labels: bug
