### ISSUE TITLE
bug: RV Manager can't build YT app on my device

### ISSUE THREAD

**Issue by Zaptyp** [ReVanced/revanced-manager#1044] opened 2023-07-20 17:47 UTC
### Type

Error while running the manager

### Bug description

RV Manager is broken I can't build app for no reason. 

### Steps to reproduce

Step 1. Try to patch youtube with default option
Step 2. Wait

### Android version

Android 13

### Manager version

1.4.1

### Target package name

com.google.android.youtube 

### Target package version.

18.23.35 (1538252224) 

### Installation type

Root

### Patches selected.

Default settings for YT 

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
07-20 18:58:35.320 10571 10579 I manager.flutter: Background concurrent copying GC freed 623861(30MB) AllocSpace objects, 17(10MB) LOS objects, 13% free, 149MB/173MB, paused 79us,43us total 697.239ms
07-20 18:58:41.540 10571 10579 I manager.flutter: Background young concurrent copying GC freed 465402(14MB) AllocSpace objects, 8(288KB) LOS objects, 0% free, 208MB/208MB, paused 4.905ms,247us total 163.545ms
07-20 18:58:42.046 10571 10578 I manager.flutter: Compiler allocated 8424KB to compile org.jf.smali.smaliParser$simple_name_return org.jf.smali.smaliParser.simple_name()
07-20 18:58:43.003 10571 10579 I manager.flutter: Background concurrent copying GC freed 2621777(105MB) AllocSpace objects, 26(888KB) LOS objects, 9% free, 216MB/240MB, paused 155us,44us total 1.462s
07-20 18:58:43.003 10571 10581 W System  : A resource failed to call close. 
07-20 18:59:09.997 10571 14271 W         : /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/res/layout/revanced_settings_with_toolbar.xml:18: error: resource drawable/yt_outline_arrow_left_black_24 (aka app.revanced.android.youtube:drawable/yt_outline_arrow_left_black_24) not found.
07-20 18:59:11.406 10571 14271 W         : error: failed linking file resources.
07-20 19:01:37.346 10571 10587 E OpenGLRenderer: Unable to match the desired swap behavior.
07-20 19:01:37.411 10571 10571 E SurfaceSyncer: Failed to find sync for id=0
07-20 19:01:37.411 10571 10571 E SurfaceSyncer: Failed to find sync for id=1
07-20 19:01:37.411 10571 10571 E SurfaceSyncer: Failed to find sync for id=2
07-20 19:01:37.411 10571 10571 E SurfaceSyncer: Failed to find sync for id=3
07-20 19:01:37.411 10571 10571 E SurfaceSyncer: Failed to find sync for id=4
07-20 19:02:00.909 10571 10587 E OpenGLRenderer: Unable to match the desired swap behavior.
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=0
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=1
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=2
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=3
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=4
07-20 19:02:00.992 10571 10571 E SurfaceSyncer: Failed to find sync for id=5
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Always autorepeat
Applied Client spoof
Applied Comments
Applied Copy video url
Applied Custom branding
Applied Disable Shorts on startup
Applied Disable auto captions
Applied Disable fullscreen panels
Applied Disable player popup panels
Applied Disable zoom haptics
Applied Enable debugging
Applied External downloads
Applied HDR auto brightness
Applied Hide Shorts components
Applied Hide ads
Applied Hide album cards
Applied Hide autoplay button
Applied Hide breaking news shelf
Applied Hide captions button
Applied Hide cast button
Applied Hide crowdfunding box
Applied Hide email address
Applied Hide endscreen cards
Applied Hide filter bar
Applied Hide floating microphone button
Applied Hide info cards
Applied Hide layout components
Applied Hide load more button
Applied Hide player buttons
Applied Hide player overlay
Applied Hide seekbar
Applied Hide timestamp
Applied Hide video action buttons
Applied Hide watch in VR
Applied Hide watermark
Applied Minimized playback
Applied Navigation buttons
Applied Old video quality menu
Applied Open links externally
Failed to apply Premium heading: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Failed to apply Remember video quality: Failed to resolve NewVideoQualityChangedFingerprint
Applied Return YouTube Dislike
Applied Seekbar tapping
Applied SponsorBlock
Applied Spoof app version
Applied Swipe controls
Applied Tablet mini player
Applied Theme
Applied Vanced MicroG support
Applied Video ads
Applied Wide searchbar
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~NP0t7yXK1JlyUd-Ripoc_g==/app.revanced.manager.flutter-bk8DfRB-h7DIemKpFMKZgg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537594816, --version-name, 18.18.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7603404840129066667.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~NP0t7yXK1JlyUd-Ripoc_g==/app.revanced.manager.flutter-bk8DfRB-h7DIemKpFMKZgg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537594816, --version-name, 18.18.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7603404840129066667.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-YRDYHY/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or video

https://cdn.discordapp.com/attachments/1131633174087209072/1131636892203491468/screen-20230720-191945.mp4

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by ILoveOpenSourceApplications** [comment] 2023-07-20 18:13
You're using a split apk. Please download the full apk (nodpi) from apkmirror and try patching again.

**Comment by Zaptyp** [comment] 2023-07-20 18:28
> You're using a split apk. Please download the full apk (nodpi) from apkmirror and try patching again.

No im not using SPLIT Apk and re vanced will not allow patching split apks

**Comment by ILoveOpenSourceApplications** [comment] 2023-07-20 20:18
The APK you downloaded could be corrupted. Try downloading again and patching.

**Comment by Zaptyp** [comment] 2023-07-20 20:20
> The APK you downloaded could be corrupted. Try downloading again and patching.

No can't be corrupted because I send this apk file from my phone to my second phone and I patched successfully

**Comment by ILoveOpenSourceApplications** [comment] 2023-07-20 20:22
Which device are you trying to patch in currently?

**Comment by Zaptyp** [comment] 2023-07-20 21:31
> Follow this:
> 
> ![image](https://user-images.githubusercontent.com/13122796/255001902-4238ddb3-2b60-48a4-b5c5-7095cb7a0ddb.png)

Clean rv install and clean yt install with the same APK I downloaded from apkmirror
https://github.com/ReVanced/revanced-manager/assets/43276401/eeadd346-f43e-4e25-9e0f-bef8bed9915b

**Comment by oSumAtrIX** [comment] 2023-07-20 21:51
Try selecting the APK file from storage. Check if it makes any difference

**Comment by Zaptyp** [comment] 2023-07-21 02:49
Look on the record I notice - -version-code is different from my app Version idk why

**Comment by oSumAtrIX** [comment] 2023-07-21 12:24
Please try as I suggested first.

**Comment by Zaptyp** [comment] 2023-07-21 12:33
> Please try as I suggested first.

... REALLY YOU DONT WATCHED MY VIDEO?

**Comment by oSumAtrIX** [comment] 2023-07-21 12:34
I did, last time ask you to do what I suggested above. Closing until then.

**Closed by oSumAtrIX** 2023-07-21 12:34 UTC
Labels: bug, question

**Comment by Zaptyp** [comment] 2023-07-21 16:28
@oSumAtrIX 

https://github.com/ReVanced/revanced-manager/assets/43276401/f9c12459-21cb-45b4-b8ab-0dda746cd6f7

**Comment by TheAabedKhan** [comment] 2023-07-21 16:49
Duplicate of #988

**Comment by KobeW50** [comment] 2023-07-25 06:42
Why is this a dupe of 988?

The user's original issue of the Manager not patching the YT app (not from storage) (and saying in the patch log the incorrect version) wasn't addressed and is seemingly not related to the exit code 1 in 988, which gave the correct version.

There have been several root users who have had the OP's issue. 

And even in the OP's last comment with the screen recording of it opening from storage is not related to 988, as it is a different error.

**Comment by TheAabedKhan** [comment] 2023-07-25 07:44
>Why is this a dupe of 988?

Because fixing 988 will automatically fix this issue as well. Both are caused due to same error even though the patching process process is different.

**Comment by Ten0** [comment] 2023-12-04 18:54
For reference: I downloaded the appropriate version from AuroraStore but I would hit this issue.
Downloading the nodpi version from apkmirror as suggested here: https://github.com/ReVanced/revanced-manager/issues/1044#issuecomment-1644377837 did work.
