### ISSUE TITLE
bug: cannot install settings patch for TikTok because its not selectable in the list of patches

### ISSUE THREAD

**Issue by GH0STDATA** [revanced/revanced-manager#592] opened 2022-12-14 23:01 UTC
### Type

Error while running the manager

### Bug description

When trying to patch TikTok `v27.2.3` using ReVanced Manager, its giving a strange error about patches depending on the `settings` patch, but `settings` is not a selectable patch in the list which is probably why its throwing the error.

### Steps to reproduce

Step 1. Download TikTok `v27.2.3` from [apkmirror](https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/tik-tok-including-musical-ly-27-2-3-release/).
Step 2. Install TikTok on Android device.
Step 3. Run ReVanced Manager and attempt to install patches for TikTok.

### Android version

Android 12

### Manager version

v0.0.50

### Target package name

com.zhiliaoapp.musically

### Target package version.

27.2.3

### Installation type

Root

### Patches selected.

Disable Login Requirement (v.0.0.1)
Downloads (v0.0.1)
Feed Filter (v0.0.1)
Fix Google Login (v0.0.1)
Hide Ads (v0.0.1)
Show Seekbar (v0.0.1)

### Device logs (exported using Manager settings).

https://pastebin.com/raw/6iGWcS4B

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: Hardcode offset changed.
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 232542704 byte allocation with 100663296 free bytes and 185MB until OOM, target footprint 443046488, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:179)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment] 2022-12-15 00:52
Settings is not a selectable patch. It is used internally by the patches, you have no control over it. This issue is a duplicate of another in the patches repository.

**Closed by oSumAtrIX** 2022-12-15 00:52 UTC
Labels: bug

**Comment by IoIxD** [comment] 2022-12-16 18:42
Could you please link said issue?

**Comment by oSumAtrIX** [comment] 2022-12-16 18:53
You can search for it with related keywords in the issues tab on this repository.

**Comment by IoIxD** [comment] 2022-12-16 19:02
No I couldn't, I tried for roughly 30 minutes.

For those who might see this while having problems with the YouTube app:  the solution was to downgrade to the version listed in the patcher. I do not use TikTok but the solution might be similar

**Comment by Sculas** [comment] 2022-12-16 19:20
@IoIxD https://github.com/revanced/revanced-patches/issues/1252

**Comment by IoIxD** [comment] 2022-12-16 19:29
> @IoIxD https://github.com/revanced/revanced-patches/issues/1248

i did see that one, and i ignored it because i misread this one and thought i was commenting on a different issue.
my problem is related to not being able to apply the settings patch due to a "NullPointerException"

**Comment by BobvdBrink22** [comment] 2023-06-28 13:37
Having this exact same problem for version 30.2.1 of TikTok.

**Comment by oSumAtrIX** [comment] 2024-02-04 15:23
This issue is outdated. For support move to our social media channels
