### ISSUE TITLE
bug: Can't pick APK file from storage

### ISSUE THREAD

**Issue by origamiofficial** [revanced/revanced-manager#136] opened 2022-09-16 16:46 UTC
### Type

Error while running the manager

### Branch

Flutter

### Bug description

Whenever I try to manually pick the YouTube apk it does nothing, show nothing. Just go back to "Patcher" tab. I haven't installed YouTube app, that's why trying to manually pick from internal storage.

### Steps to reproduce

Manually pick YouTube apk file from storage.

### Relevant log output

```shell
--------- beginning of crash
09-16 22:23:20.387  3454  3454 E AndroidRuntime: FATAL EXCEPTION: main
09-16 22:23:20.387  3454  3454 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 3454
09-16 22:23:20.387  3454  3454 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7893)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8613)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
09-16 22:23:20.387  3454  3454 E AndroidRuntime: 	... 13 more
--------- beginning of main
09-16 22:23:47.029  3972  3972 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10414; state: ENABLED
09-16 22:23:47.035  3972  4634 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:23:47.056  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:23:47.056  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:23:47.879  3972  3993 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
09-16 22:23:47.886  3972  3995 W System  : A resource failed to call close. 
09-16 22:23:48.155  3972  4634 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:23:48.157  3972  4634 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@2171061]
--------- beginning of system
09-16 22:23:48.181  3972  3972 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:23:48.247  3972  4008 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:23:50.111  3972  3972 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:23:50.112  3972  3972 D FilePickerDelegate: Selected type */*
09-16 22:23:53.525  3972  4746 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:23:53.537  3972  4746 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:23:53.537  3972  4746 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@3638eb1]
09-16 22:23:53.552  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:23:53.552  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:23:53.552  3972  3972 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:23:53.571  3972  3972 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:23:53.587  3972  4008 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:24:31.791  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:24:31.791  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:24:31.791  3972  3972 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:24:31.791  3972  3972 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:24:33.532  3972  3972 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:24:33.543  3972  3972 D FilePickerDelegate: Selected type */*
09-16 22:24:36.502  3972  5730 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:24:36.512  3972  5730 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:24:36.512  3972  5730 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@42d700b]
09-16 22:24:36.528  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:24:36.529  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:24:36.529  3972  3972 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:24:36.529  3972  3972 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:24:36.529  3972  3972 E SurfaceSyncer: Failed to find sync for id=4
09-16 22:24:36.547  3972  3972 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:24:36.569  3972  4008 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:24:41.858  3972  3972 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:24:41.860  3972  3972 D FilePickerDelegate: Selected type */*
09-16 22:24:43.638  3972  5822 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:24:43.654  3972  5822 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:24:43.655  3972  5822 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@d9f84f9]
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=4
09-16 22:24:43.663  3972  3972 E SurfaceSyncer: Failed to find sync for id=5
09-16 22:24:43.680  3972  3972 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:24:43.702  3972  4008 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=4
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=5
09-16 22:25:05.979  3972  3972 E SurfaceSyncer: Failed to find sync for id=6
09-16 22:25:24.349  6493  6493 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
09-16 22:25:24.350  6493  6493 W manager.flutter: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
09-16 22:25:24.359  6493  6493 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10414; state: ENABLED
09-16 22:25:24.384  6493  6493 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-16 22:25:24.384  6493  6493 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
09-16 22:25:24.384  6493  6493 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-16 22:25:24.385  6493  6493 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-16 22:25:24.385  6493  6493 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-16 22:25:24.404  6493  6493 W manager.flutter: type=1400 audit(0.0:47631): avc: denied { read } for name="max_map_count" dev="proc" ino=648539 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: QUALCOMM build                   : 8e5405b, I57aaec3440
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Build Date                       : 05/21/21
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.10
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Local Branch                     : mybranchebba1dbe-451b-f160-ac81-1458d0b52ae8
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r135-rel
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Remote Branch                    : NONE
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-16 22:25:24.423  6493  6493 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-16 22:25:24.426  6493  6493 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
09-16 22:25:25.151  6493  6516 I flutter : dynamic_color: Core palette detected.
09-16 22:25:25.177  6493  6493 W System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
09-16 22:25:25.177  6493  6493 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-16 22:25:25.177  6493  6493 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-16 22:25:25.177  6493  6493 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-16 22:25:25.177  6493  6493 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-16 22:25:25.177  6493  6493 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-16 22:25:25.177  6493  6493 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-16 22:25:25.178  6493  6493 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-16 22:25:25.178  6493  6493 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-16 22:25:25.178  6493  6493 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-16 22:25:25.178  6493  6493 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-16 22:25:25.178  6493  6493 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-16 22:25:25.178  6493  6493 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-16 22:25:25.178  6493  6493 W System.err: 	at android.os.Handler.handleCallback(Handler.java:942)
09-16 22:25:25.178  6493  6493 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-16 22:25:25.178  6493  6493 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
09-16 22:25:25.178  6493  6493 W System.err: 	at android.os.Looper.loop(Looper.java:288)
09-16 22:25:25.178  6493  6493 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7893)
09-16 22:25:25.178  6493  6493 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 22:25:25.178  6493  6493 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
09-16 22:25:25.178  6493  6493 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-16 22:25:25.178  6493  6493 W System.err: Caused by: java.io.IOException: error=13, Permission denied
09-16 22:25:25.178  6493  6493 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-16 22:25:25.178  6493  6493 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-16 22:25:25.178  6493  6493 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-16 22:25:25.178  6493  6493 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-16 22:25:25.178  6493  6493 W System.err: 	... 19 more
09-16 22:25:25.178  6493  6517 I Gralloc4: mapper 4.x is not supported
09-16 22:25:25.179  6493  6517 W Gralloc3: mapper 3.x is not supported
09-16 22:25:25.180  6493  6517 W Gralloc4: allocator 4.x is not supported
09-16 22:25:25.181  6493  6517 W Gralloc3: allocator 3.x is not supported
09-16 22:25:25.198  6493  6562 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-16 22:25:25.198  6493  6562 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-16 22:25:25.205  6493  6493 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:25.215  6493  6511 W Parcel  : Expecting binder but got null!
09-16 22:25:28.172  6493  6493 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:25:28.174  6493  6493 D FilePickerDelegate: Selected type */*
09-16 22:25:29.645  6493  6493 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10414; state: ENABLED
09-16 22:25:29.657  6493  6633 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:25:29.667  6493  6633 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:25:29.667  6493  6633 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@1cb157f]
09-16 22:25:29.677  6493  6493 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:29.677  6493  6493 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:25:29.695  6493  6493 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:25:29.733  6493  6516 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:25:31.704  6493  6493 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:25:31.708  6493  6493 D FilePickerDelegate: Selected type */*
09-16 22:25:32.999  6493  6688 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:25:33.005  6493  6688 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:25:33.005  6493  6688 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@92e432d]
09-16 22:25:33.027  6493  6493 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:33.027  6493  6493 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:25:33.027  6493  6493 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:25:33.049  6493  6493 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:25:33.071  6493  6516 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:25:41.552  6493  6493 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:25:41.553  6493  6493 D FilePickerDelegate: Selected type */*
09-16 22:25:42.702  6493  6503 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
09-16 22:25:42.974  6493  6896 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:25:42.984  6493  6896 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:25:42.984  6493  6896 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@9e2d20f]
09-16 22:25:42.994  6493  6493 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:42.994  6493  6493 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:25:42.994  6493  6493 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:25:42.994  6493  6493 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:25:43.014  6493  6493 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:25:43.045  6493  6516 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-16 22:25:49.046  6493  6493 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-16 22:25:49.047  6493  6493 D FilePickerDelegate: Selected type */*
09-16 22:25:50.622  6493  7011 I FilePickerUtils: Caching from URI: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fyoutube.apk
09-16 22:25:50.634  6493  7011 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk
09-16 22:25:50.634  6493  7011 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@eb85953]
09-16 22:25:50.638  6493  6493 E SurfaceSyncer: Failed to find sync for id=0
09-16 22:25:50.638  6493  6493 E SurfaceSyncer: Failed to find sync for id=1
09-16 22:25:50.638  6493  6493 E SurfaceSyncer: Failed to find sync for id=2
09-16 22:25:50.638  6493  6493 E SurfaceSyncer: Failed to find sync for id=3
09-16 22:25:50.638  6493  6493 E SurfaceSyncer: Failed to find sync for id=4
09-16 22:25:50.658  6493  6493 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/youtube.apk Binary XML file line #41
09-16 22:25:50.681  6493  6516 I flutter : type 'Null' is not a subtype of type 'String' in type cast
```

### Additional context

Android Version: 13
Rom: EvolutionX
Device: OnePlus 6T
Manager Version: 0.0.7

**Comment by Aunali321** [comment] 2022-09-16 17:08
Duplicate of #93.

**Closed by Aunali321** 2022-09-16 17:08 UTC
Labels: bug
