### ISSUE TITLE
feat: Patch overview screen

### ISSUE THREAD

**Issue by ViktorVoloshko** [revanced/revanced-manager#139] opened 2022-09-16 16:57 UTC
### Type

Functionality

### Branch

Flutter

### Issue

When I used Manager for first time I tried to patch Split-APK which is unsupported (hope this'll be fixed soon) but at least I got warning. Then I downloaded latest stable app and tried it. I got info about patches and recommended (read as supported) versions of APKs only when it came to chose what patches I want to apply. Only then I redownloaded right version of APK which is recommended and it went well.

TL;DR: You don't know what version is recommended until you reach point where choosing patches.

### Feature

I suggest creating screen with overview of all patches to all apps where you should be able to see:
1) Patch name
2) Patch description
3) Supported versions of patch
4) (Maybe when Manager will be closer to release) screenshots or short GIFs with demonstration of results

### Motivation

Of course it's a timesaving QoL improvement and ability to know what exactly patch do.

**Comment by Aunali321** [comment] 2022-09-16 17:07
Duplicate of #86.

**Closed by Aunali321** 2022-09-16 17:07 UTC
Labels: feature-request
