### ISSUE TITLE
feat: Allow to export/import keystore

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#471] opened 2022-11-02 13:05 UTC
### Type

Functionality

### Issue

For some unknown reason, when you install a newer patched version of Youtube, it fails because the apk signature changed from the previous file.

So it would be great if you can export and import the keystore to avoid the issue.

### Feature

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-11-02 13:08
Dupe of #263. If you can't wait, check custom- keystore branch and build manager from source.

**Closed by Aunali321** 2022-11-02 13:08 UTC
Labels: feature-request
