### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Zexerif** [revanced/revanced-manager#759] opened 2023-03-25 02:03 UTC
### Type

Error while running the manager

### Bug description

Item with package name still exists 

### Steps to reproduce

I just tried to download it

### Android version

Version: 0.0.57
Model: Pixel 6a
Android Version: 13
Arch: arm64-v8a

### Manager version

Version: 0.0.57
Model: Pixel 6a
Android Version: 13
Arch: arm64-v8a

### Target package name

Any

### Target package version.

Any

### Installation type

Non-root

### Patches selected.

Any

### Device logs (exported using Manager settings).

```shell
https://drive.google.com/drive/folders/13W0mgt_ISDrE-vFUMuN54_068BIPxmvJ
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-25 04:31
Can you specify what the issue you're facing in detail?

**Comment by Ushie** [comment] 2023-03-25 07:59
Dupe of #494, uninstall the app before clicking install in ReVanced Manager

**Closed by Ushie** 2023-03-25 07:59 UTC
Labels: bug
