### ISSUE TITLE
feat: Option to choose a version of youtube that supports all patches from a dropdown using an online repository of apks

### ISSUE THREAD

**Issue by rsmyst** [revanced/revanced-manager#92] opened 2022-09-15 09:05 UTC
### Type

Functionality

### Branch

The app...

### Issue

Currently, revanced manager just looks for existing apk of youtube and tries to patch that. since the latest version of youtube doesn't support many useful patches, it's inconvinient to download an apk manually.

### Feature

Searches cloud repo for latest youtube apk that supports all features. 

### Motivation

it'd make it easier for a first time user like myself.

**Comment by rollingmoai** [comment] 2022-09-15 09:17
Duplicate of #12

**Comment by ponces** [comment] 2022-09-15 10:36
Out of scope for Manager.
Check https://github.com/revanced/revanced-manager/issues/12#issuecomment-1173425358.

**Closed by ponces** 2022-09-15 10:36 UTC
Labels: feature-request
