### ISSUE TITLE
bug: Can't choose language

### ISSUE THREAD

**Issue by OwenXP** [revanced/revanced-manager#537] opened 2022-11-25 08:23 UTC
### Type

Error while running the manager

### Bug description

If I chose other language than English,  The program's text is getting weird.

### Steps to reproduce

Step 1 : Change app language.
Stap 2 : The program's text is getting weird.

### Android version

Android 13

### Manager version

0.0.41

### Target package name

X

### Target package version.

X

### Installation type

Non-root

### Patches selected.

X

### Device logs (exported using Manager settings).

```shell
X
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
X
```

### Screenshots or videos

![Screenshot_20221125-170939](https://user-images.githubusercontent.com/91373043/203934421-0fe5cd35-c4f7-46e9-a040-bb1a8f4c39bc.png)

### Solution

Idk

### Additional context

Please fix it.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by xerta555** [comment] 2022-11-26 02:31
In my case i have even no languages in the list.

**Comment by CennoxX** [comment] 2022-11-26 23:14
Duplicate of #530

**Closed** 2022-11-28 17:09 UTC
Labels: bug
