### ISSUE TITLE
bug: <YouTube music and YouTube patches crash in 0.09 while being patched>

### ISSUE THREAD

**Issue by Vegetagiy123** [revanced/revanced-manager#173] opened 2022-09-17 19:21 UTC
### Type

Error while running the manager

### Branch

The apk paring still crashes when I patch YouTube and YouTube music it immediately closes and stopes working 

### Bug description

I found the bug when I was trying to patch YouTube and YouTube music and the Revanced manger immediately crashes 

### Steps to reproduce

Step 1 fix the patches from crashing the manger
Step 2 fix manger 

### Relevant log output

```shell
YouTube  and YouTube music manger keeps crashing when the apk files are patching
```

### Screenshots or videos

![Screenshot_20220917-122106](https://user-images.githubusercontent.com/113322179/190873224-b3e98f72-f946-4838-b4d5-f226d43e9fe1.png)

**Comment by pietryszak** [comment] 2022-09-17 19:25
@Vegetagiy123 Duplicate of https://github.com/revanced/revanced-manager/issues/172

**Closed** 2022-09-17 19:26 UTC
Labels: bug
