### ISSUE TITLE
Pach in Bacraund

### ISSUE THREAD

**Issue by NotHuza** [revanced/revanced-manager#748] opened 2023-03-19 09:26 UTC
### Type

Functionality

### Issue

you can't put app in bacraund
example if you put the application in bakraund and go to write in discord and come back after an hour, the progress will continue where I left it.

### Feature

place the app so that it can track progress in the background, for example put it in a status notification that tracks progress

### Motivation

waiting while on the boring screen just for the patch to be ready for 20 minutes
and making sure that my screen does not lock

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by EvadeMaster** [comment] 2023-03-19 09:29
Duplicate of #684

**Closed by EvadeMaster** 2023-03-19 09:29 UTC
Labels: feature-request

**Comment by NotHuza** [comment] 2023-03-19 09:31
Oh i not saw that

**Comment by Neglectfull** [comment] 2023-04-11 11:41
Spell background correctly, its bugging be a ton lol :)
