### ISSUE TITLE
feat: Remember Patches Set / Restore for Updates or New Installations

### ISSUE THREAD

**Issue by megamorphg** [revanced/revanced-manager#465] opened 2022-11-01 17:47 UTC
### Type

Functionality

### Issue

With dozens of patches available for Youtube app, every time someone wants to re-install or upgrade, they have to carefully select each patch they want. It can take a minute or two just selecting the desired patches.

### Feature

When selecting the patches, have an option to save or restore patch set.

### Motivation

Saves time testing, updating and re-installing.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by CennoxX** [comment] 2022-11-02 10:10
Duplicate of  #321.

**Closed** 2022-11-02 11:04 UTC
Labels: feature-request
