### ISSUE TITLE
Black screen when opening the manager

### ISSUE THREAD

**Issue by Sarreos** [revanced/revanced-manager#498] opened 2022-11-10 16:23 UTC
### Type

Error at runtime

### Bug description

When app is opened there is just a black screen. Force closing doesn't help rebooting doesn't help either. It just happends randomly. 

### Steps to reproduce

Open revanced manager

### Android version

12

### Manager version

0.0.39 happends on other versions too

### Target package name

Not relevant

### Target package version.

Not relevant 

### Installation type

Non-root

### Patches selected.

Not relevent

### Device logs (exported using Manager settings).

```shell
Can't access the logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-11-10 16:51
dupe of #379

**Closed by Aunali321** 2022-11-10 16:51 UTC
Labels: bug
