### ISSUE TITLE
bug: Manager Update Card with Weird UI

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-manager#969] opened 2023-06-24 17:12 UTC
### Type

Cosmetic

### Bug description

ReVanced Manager update card shows an weird ui if you cancel it & try to start the update again.

It fixes after kill the app from background.

### Steps to reproduce

- Open ReVanced Manager
- Tap Update
- Cancel downloading update in the middle
- Tap update button again
- See the ui

### Android version

13

### Manager version

1.3.5

### Target package name

app.revanced.manager.flutter

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
06-24 23:10:57.485  3367  3384 E OpenGLRenderer: Unable to match the desired swap behavior.
06-24 23:10:57.491  3367  3367 E SurfaceSyncer: Failed to find sync for id=0
06-24 23:10:57.491  3367  3367 E SurfaceSyncer: Failed to find sync for id=1
```

### Screenshots or videos

https://github.com/revanced/revanced-manager/assets/82371061/cf6f890e-a742-48de-8436-f2ee53c9d763

### Solution

Fix the UI even if I cancel downloading the updates

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment] 2023-06-24 19:14
Duplicate of #936 and it's fixed in the latest manager version as well.

**Closed by ILoveOpenSourceApplications** 2023-06-24 19:14 UTC
Labels: bug
