### ISSUE TITLE
bug: Patch selector search bugged

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2058] opened 2024-07-13 22:05 UTC
### Bug description

May be caused by compose m3 update:

![image](https://github.com/user-attachments/assets/eccd27de-5cf6-4239-bef8-2a2a70a3731b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment] 2024-07-20 14:05
It was indeed caused by the m3 update. It has been fixed in the downloader branch, which has the update.

**Closed by Axelen123** 2024-07-20 14:05 UTC
Labels: Bug report, ReVanced Manager Compose
