### ISSUE TITLE
feat: Ability to select Xpapk, apks or apkm file. 

### ISSUE THREAD

**Issue by hridoysarkar050** [revanced/revanced-manager#315] opened 2022-09-27 04:10 UTC
### Type

Functionality

### Issue

After downloading from online mirror website like Apkpure, YouTube app is in xapk format. But ReVanced Manager doesn't support Xapk files. 

### Feature

Please add support for Xapk files. So we can patch xapk files.

### Motivation

It would be really convenient.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment] 2022-09-27 04:35
Dupe of #135.

**Comment by Aunali321** [comment] 2022-09-27 04:35
Needs to be supported by revanced patcher.

**Closed by oSumAtrIX** 2022-09-27 04:35 UTC
Labels: feature-request
