### ISSUE TITLE
bug: doubles every time you reloaded

### ISSUE THREAD

**Issue by Joaquin0apps** [revanced/revanced-manager#175] opened 2022-09-17 19:36 UTC
### Type

Cosmetic

### Branch

.....

### Bug description

YouTube vanced component is repeated 
![Screenshot_2022-09-17-15-24-54-704_app revanced manager flutter](https://user-images.githubusercontent.com/55076853/190873753-ca5912be-7445-41d7-aeed-76bc082eb02c.jpg)

### Steps to reproduce

Reload the app several times

### Relevant log output

```shell
--------- beginning of main
09-17 15:19:08.843 11446 11446 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-17 15:19:09.258 11446 11446 I FeatureParser: can't find lancelot.xml in assets/device_features/,it may be in /vendor/etc/device_features
09-17 15:19:09.265 11446 11446 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
09-17 15:19:09.262 11446 11446 W manager.flutter: type=1400 audit(0.0:513377): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16607 scontext=u:r:untrusted_app:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
09-17 15:19:09.466 11446 11446 W manager.flutter: type=1400 audit(0.0:513378): avc: denied { read } for name="max_map_count" dev="proc" ino=15652247 scontext=u:r:untrusted_app:s0:c85,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
09-17 15:19:09.525 11446 11446 I GPUD    : @gpudInitialize: successfully initialized with GL, dbg=0 mmdump_dbg=0
09-17 15:19:09.739 11446 11446 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@84ae21d
09-17 15:19:09.750 11446 11446 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@8354c92
09-17 15:19:09.755 11446 11446 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:19:09.756 11446 11446 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:19:09.756 11446 11446 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:19:09.762 11446 11446 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@84ae21d
09-17 15:19:09.763 11446 11446 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
09-17 15:19:09.805 11446 11446 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@84ae21d
--------- beginning of system
09-17 15:19:09.808 11446 11446 W Activity: Slow Operation: Activity app.revanced.manager.flutter/.MainActivity onCreate took 503ms
09-17 15:19:09.806 11446 11446 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:19:09.806 11446 11446 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@84ae21d
09-17 15:19:10.051 11446 11446 I PowerHalWrapper: PowerHalWrapper.getInstance 
09-17 15:19:10.062 11446 11446 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 387ms late (wall=791ms running=105ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 2 msg, msg 2 took 380ms (seq=2 running=67ms runnable=5ms io=282ms late=12ms h=android.app.ActivityThread$H w=110)
09-17 15:19:10.062 11446 11446 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 1178ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 380ms (seq=2 running=67ms runnable=5ms io=282ms late=12ms h=android.app.ActivityThread$H w=110), msg 3 took 791ms (seq=3 running=105ms runnable=3ms io=434ms late=387ms h=android.app.ActivityThread$H w=159)
09-17 15:19:10.130 11446 11446 D SurfaceView: UPDATE null, mIsCastMode = false
09-17 15:19:10.136 11446 11487 D Surface : Surface::connect(this=0x7e05ab4000,api=1)
09-17 15:19:10.138 11446 11487 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:19:10.138 11446 11487 D Surface : Surface::setBufferCount(this=0x7e05ab4000,bufferCount=3)
09-17 15:19:10.138 11446 11506 D Surface : Surface::connect(this=0x7bf7b28000,api=1)
09-17 15:19:10.139 11446 11506 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:19:10.146 11446 11446 D ViewRootImpl: setSurfaceViewCreated, created:true
09-17 15:19:11.315 11446 11505 I flutter : dynamic_color: Dynamic color not detected on this device.
09-17 15:19:11.349 11446 11506 W Gralloc3: mapper 3.x is not supported
09-17 15:19:11.374 11557 11557 W su      : type=1400 audit(0.0:513387): avc: denied { read } for name="bin" dev="dm-4" ino=38 scontext=u:r:magisk_client:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
09-17 15:19:11.429 11446 11506 E gralloc : Arm Module v1.0
09-17 15:19:11.430 11446 11506 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-17 15:19:11.634 11446 11505 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_500_ec3a64e46e2ee5f546845582e1d5409107780cef55bc43b052ee962f9807aee6.ttf'
09-17 15:19:11.641 11446 11505 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Roboto_regular_d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf'
09-17 15:19:11.684 11446 11505 I flutter : saving File: '/data/user/0/app.revanced.manager.flutter/files/Inter_regular_ca30a452e6f1961d934a7c782130cbcba3bbb9b611aae1dac1279d396350b35e.ttf'
09-17 15:19:17.222 11446 11485 I manager.flutte: ProcessProfilingInfo new_methods=1464 is saved saved_to_disk=1 resolve_classes_delay=8000
09-17 15:19:18.269 11446 11446 W Looper  : Slow Looper main: Long Msg: seq=104 plan=15:19:11.349  late=2ms wall=6918ms running=7ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0
09-17 15:19:18.283 11446 11446 I Choreographer: Skipped 415 frames!  The application may be doing too much work on its main thread.
09-17 15:19:18.304 11446 11487 I OpenGLRenderer: Davey! duration=6942ms; Flags=0, IntendedVsync=133855842721194, Vsync=133862765156084, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=133862767056661, AnimationStart=133862767183738, PerformTraversalsStart=133862767187200, DrawStart=133862768733046, SyncQueued=133862771637354, SyncStart=133862772428431, IssueDrawCommandsStart=133862773251508, SwapBuffers=133862781378585, FrameCompleted=133862785814277, DequeueBufferDuration=4846000, QueueBufferDuration=1791000, 
09-17 15:19:18.306 11446 11446 W Looper  : Slow Looper main: doFrame is 6924ms late because of 2 msg, msg 1 took 6918ms (seq=104 running=7ms late=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
09-17 15:19:18.338 11446 11446 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 5567ms late (wall=1ms running=1ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 8 msg, msg 1 took 6918ms (seq=104 running=7ms late=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
09-17 15:19:18.350 11446 11446 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 5565ms late (wall=11ms running=1ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem }) because of 9 msg, msg 1 took 6918ms (seq=104 running=7ms late=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
09-17 15:19:18.378 11856 11856 W su      : type=1400 audit(0.0:513418): avc: denied { read } for name="bin" dev="dm-4" ino=38 scontext=u:r:magisk_client:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
09-17 15:19:18.549 11446 11487 D Surface : Surface::disconnect(this=0x7e05ab4000,api=1)
09-17 15:19:18.551 11446 11487 D Surface : Surface::connect(this=0x7e05ab4000,api=1)
09-17 15:19:18.552 11446 11487 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:19:18.552 11446 11487 D Surface : Surface::setBufferCount(this=0x7e05ab4000,bufferCount=3)
09-17 15:19:19.243 11446 11855 W manager.flutte: resources.arsc in APK '/data/app/pro.anioload.animecenter-vh7vot4HMOJgxCyQq_6m_w==/base.apk' is compressed.
09-17 15:19:19.320 11446 11855 W manager.flutte: resources.arsc in APK '/data/app/com.snaptube.premium-ZQ5GYvIdw7cjV2EU6q5Xkg==/base.apk' is compressed.
09-17 15:19:50.020 11446 11506 D Surface : Surface::disconnect(this=0x7bf7b28000,api=1)
09-17 15:19:50.021 11446 11446 D ViewRootImpl: setSurfaceViewCreated, created:false
09-17 15:19:50.021 11446 11446 D Surface : Surface::disconnect(this=0x7bf7b28000,api=-1)
09-17 15:19:50.026 11446 11487 D Surface : Surface::disconnect(this=0x7e05ab4000,api=1)
09-17 15:19:50.033 11446 11487 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 29, oppidx_max 29, oppidx_min 0
09-17 15:19:54.955 11446 11487 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 29, oppidx_max 29, oppidx_min 0
09-17 15:22:43.533 11446 11506 D Surface : Surface::connect(this=0x7e05be0000,api=1)
09-17 15:22:43.534 11446 11506 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:22:43.534 11446 11446 D ViewRootImpl: setSurfaceViewCreated, created:true
09-17 15:22:43.549 11446 11487 D Surface : Surface::connect(this=0x7bf7b27000,api=1)
09-17 15:22:43.550 11446 11487 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:22:43.550 11446 11487 D Surface : Surface::setBufferCount(this=0x7bf7b27000,bufferCount=3)
09-17 15:24:01.287 11446 11855 W manager.flutte: resources.arsc in APK '/data/app/pro.anioload.animecenter-vh7vot4HMOJgxCyQq_6m_w==/base.apk' is compressed.
09-17 15:24:01.355 11446 11855 W manager.flutte: resources.arsc in APK '/data/app/com.snaptube.premium-ZQ5GYvIdw7cjV2EU6q5Xkg==/base.apk' is compressed.
09-17 15:24:01.719 11446 11446 W manager.flutte: Long monitor contention with owner pool-1-thread-1 (11855) at long android.content.res.ApkAssets.nativeLoad(java.lang.String, boolean, boolean, boolean)(ApkAssets.java:-2) waiters=0 in java.util.ArrayList android.app.ActivityThread.collectComponentCallbacks(boolean, android.content.res.Configuration) for 171ms
09-17 15:24:59.261 11446 11506 D Surface : Surface::disconnect(this=0x7e05be0000,api=1)
09-17 15:24:59.264 11446 11446 D ViewRootImpl: setSurfaceViewCreated, created:false
09-17 15:24:59.264 11446 11446 D Surface : Surface::disconnect(this=0x7e05be0000,api=-1)
09-17 15:24:59.267 11446 11487 D Surface : Surface::disconnect(this=0x7bf7b27000,api=1)
09-17 15:24:59.276 11446 11487 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 29, oppidx_max 29, oppidx_min 0
09-17 15:29:22.992 16967 16967 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-17 15:29:23.201 16967 16967 I FeatureParser: can't find lancelot.xml in assets/device_features/,it may be in /vendor/etc/device_features
09-17 15:29:23.202 16967 16967 W manager.flutter: type=1400 audit(0.0:516098): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16607 scontext=u:r:untrusted_app:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
09-17 15:29:23.206 16967 16967 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
09-17 15:29:23.341 16967 16967 I GPUD    : @gpudInitialize: successfully initialized with GL, dbg=0 mmdump_dbg=0
09-17 15:29:23.402 16967 16967 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:29:23.415 16967 16967 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@a2c5260
09-17 15:29:23.431 16967 16967 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:29:23.431 16967 16967 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:29:23.431 16967 16967 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:29:23.432 16967 16967 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:29:23.433 16967 16967 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
09-17 15:29:23.479 16967 16967 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:29:23.480 16967 16967 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:29:23.480 16967 16967 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:29:23.526 16967 16967 I PowerHalWrapper: PowerHalWrapper.getInstance 
09-17 15:29:23.533 16967 16967 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 518ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 189ms (seq=2 running=60ms runnable=2ms io=116ms late=6ms h=android.app.ActivityThread$H w=110), msg 3 took 326ms (seq=3 running=76ms runnable=2ms io=157ms late=193ms h=android.app.ActivityThread$H w=159)
09-17 15:29:23.585 16967 16967 D SurfaceView: UPDATE null, mIsCastMode = false
09-17 15:29:23.591 16967 16993 D Surface : Surface::connect(this=0x7d0017b000,api=1)
09-17 15:29:23.592 16967 16993 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:29:23.592 16967 16993 D Surface : Surface::setBufferCount(this=0x7d0017b000,bufferCount=3)
09-17 15:29:23.593 16967 16999 D Surface : Surface::connect(this=0x7d002d9000,api=1)
09-17 15:29:23.594 16967 16999 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:29:23.597 16967 16967 D ViewRootImpl: setSurfaceViewCreated, created:true
09-17 15:29:24.491 16967 16998 I flutter : dynamic_color: Dynamic color not detected on this device.
09-17 15:29:24.544 16967 16999 W Gralloc3: mapper 3.x is not supported
09-17 15:29:24.562 17033 17033 W su      : type=1400 audit(0.0:516104): avc: denied { read } for name="bin" dev="dm-4" ino=38 scontext=u:r:magisk_client:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
09-17 15:29:24.631 16967 16999 E gralloc : Arm Module v1.0
09-17 15:29:24.633 16967 16999 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-17 15:29:24.774 17054 17054 W su      : type=1400 audit(0.0:516105): avc: denied { read } for name="bin" dev="dm-4" ino=38 scontext=u:r:magisk_client:s0:c85,c257,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
09-17 15:29:25.560 16967 17065 W manager.flutte: resources.arsc in APK '/data/app/pro.anioload.animecenter-vh7vot4HMOJgxCyQq_6m_w==/base.apk' is compressed.
09-17 15:29:25.622 16967 17065 W manager.flutte: resources.arsc in APK '/data/app/com.snaptube.premium-ZQ5GYvIdw7cjV2EU6q5Xkg==/base.apk' is compressed.
09-17 15:29:29.750 16967 16999 D Surface : Surface::disconnect(this=0x7d002d9000,api=1)
09-17 15:29:29.751 16967 16967 D ViewRootImpl: setSurfaceViewCreated, created:false
09-17 15:29:29.752 16967 16967 D Surface : Surface::disconnect(this=0x7d002d9000,api=-1)
09-17 15:29:29.755 16967 16993 D Surface : Surface::disconnect(this=0x7d0017b000,api=1)
09-17 15:29:29.777 16967 16993 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 29, oppidx_max 29, oppidx_min 0
09-17 15:30:18.564 17543 17543 E manager.flutte: Not starting debugger since process cannot load the jdwp agent.
09-17 15:30:18.684 17543 17543 I FeatureParser: can't find lancelot.xml in assets/device_features/,it may be in /vendor/etc/device_features
09-17 15:30:18.685 17543 17543 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
09-17 15:30:18.838 17543 17543 I GPUD    : @gpudInitialize: successfully initialized with GL, dbg=0 mmdump_dbg=0
09-17 15:30:18.969 17543 17543 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:30:18.974 17543 17543 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@a2c5260
09-17 15:30:18.992 17543 17543 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:30:18.992 17543 17543 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:30:18.992 17543 17543 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
09-17 15:30:18.993 17543 17543 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:30:18.994 17543 17543 W manager.flutte: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
09-17 15:30:19.030 17543 17543 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:30:19.031 17543 17543 I chatty  : uid=10341(app.revanced.manager.flutter) identical 1 line
09-17 15:30:19.031 17543 17543 D ForceDarkHelper: updateByCheckExcludeList: pkg: app.revanced.manager.flutter activity: app.revanced.manager.flutter.MainActivity@8354c92
09-17 15:30:19.089 17543 17543 I PowerHalWrapper: PowerHalWrapper.getInstance 
09-17 15:30:19.097 17543 17543 W Looper  : Slow Looper main: Activity app.revanced.manager.flutter/.MainActivity is 519ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 106ms (seq=2 running=58ms runnable=1ms io=39ms late=5ms h=android.app.ActivityThread$H w=110), msg 3 took 410ms (seq=3 running=75ms runnable=2ms io=212ms late=109ms h=android.app.ActivityThread$H w=159)
09-17 15:30:19.141 17543 17543 D SurfaceView: UPDATE null, mIsCastMode = false
09-17 15:30:19.146 17543 17574 D Surface : Surface::connect(this=0x7d00300000,api=1)
09-17 15:30:19.146 17543 17574 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:30:19.152 17543 17543 D ViewRootImpl: setSurfaceViewCreated, created:true
09-17 15:30:19.152 17543 17567 D Surface : Surface::connect(this=0x7d00198000,api=1)
09-17 15:30:19.153 17543 17567 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-17 15:30:19.153 17543 17567 D Surface : Surface::setBufferCount(this=0x7d00198000,bufferCount=3)
09-17 15:30:20.093 17543 17572 I flutter : dynamic_color: Dynamic color not detected on this device.
09-17 15:30:20.139 17543 17574 W Gralloc3: mapper 3.x is not supported
09-17 15:30:20.212 17543 17574 E gralloc : Arm Module v1.0
09-17 15:30:20.219 17543 17574 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-17 15:30:21.228 17543 17638 W manager.flutte: resources.arsc in APK '/data/app/pro.anioload.animecenter-vh7vot4HMOJgxCyQq_6m_w==/base.apk' is compressed.
09-17 15:30:21.299 17543 17638 W manager.flutte: resources.arsc in APK '/data/app/com.snaptube.premium-ZQ5GYvIdw7cjV2EU6q5Xkg==/base.apk' is compressed.
```

### Screenshots or videos

![Screenshot_2022-09-17-15-24-54-704_app revanced manager flutter](https://user-images.githubusercontent.com/55076853/190873460-bcdd4e15-8c89-4c27-a597-4f1f46e87d0c.jpg)
.

### Solution

reinstall the app 

### Additional context

Nada

**Comment by pietryszak** [comment] 2022-09-17 19:37
Duplicate of https://github.com/revanced/revanced-manager/issues/174

**Closed** 2022-09-17 19:39 UTC
Labels: bug
