### ISSUE TITLE
bug: Manager does not start since version 0.30 LineageOS 18.1

### ISSUE THREAD

**Issue by viniribeirossa** [revanced/revanced-manager#382] opened 2022-10-11 00:17 UTC
### Type

Error at runtime

### Bug description

The app installs, however, when I open it, it stays on this black screen
![Screenshot_20221010-210538_ReVanced_Manager](https://user-images.githubusercontent.com/57050698/194970669-92ad7eb5-5e61-4e5d-8ce4-034aee99f4f1.png)

### Steps to reproduce

Install
Run

### Android version

LineageOS 18.1

### Manager version

v0.30

### Target package name

revanced

### Target package version.

revanced 

### Installation type

Root

### Patches selected.

revanced 

### Device logs (exported using Manager settings).

```shell
it is not possible because the application does not start
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-11 07:12
Dupe of #379.

**Closed by Aunali321** 2022-10-11 07:12 UTC
Labels: bug
