### ISSUE TITLE
bug: Manager fails to launch after changing to a different GitHub source

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-manager#989] opened 2023-07-02 20:44 UTC
### Type

Error while running the manager

### Bug description

If the GitHub source is changed from 'revanced' to a different GitHub user, manager fails to start and remains stuck on the splash screen.

### Steps to reproduce

- open Manager Settings -> Sources
- change 'patches organization' from `revanced` to any other GitHub user (such as `LisoUseInAIKyrios`)
- close and restart Manager

Manager will not launch, and will remain stuck on the app splash screen.

### Manager version

1.3.8

### Device logs (exported using Manager settings).

```
Cannot export logs, app fails to launch
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment] 2023-07-03 13:35
Duplicate of #982

**Closed as completed** 2023-07-03 15:26 UTC
Labels: Bug report

**Comment by Novgorod** [comment] 2023-07-03 17:52
> 982 needs it's title updated to reflect the problem (using a custom source)

I edited it.
