### ISSUE TITLE
bug: ReVanced refuses to start past splash screen

### ISSUE THREAD

**Issue by Dondrejohnson5** [revanced/revanced-manager#398] opened 2022-10-15 16:03 UTC
### Type

Other

### Bug description

The bug occurs in version 0.0.30 and up. 0.0.29 is the latest version without this issue

### Steps to reproduce

Step 1: download v0.0.29 and open it
Step 2: download the latest version (v0.0.30 or later), update, and open the app again. You still see you are stuck on either a blank white screen or a splash screen

### Android version

Android 12.1

### Manager version

0.0.32

### Target package name

None

### Target package version.

Not applicable

### Installation type

Non-root

### Patches selected.

Not applicable

### Device logs (exported using Manager settings).

```shell
Could not extract log
```

### Screenshots or videos

![Screenshot_20221015-120253](https://user-images.githubusercontent.com/29732079/195996321-212fc832-0871-4787-ada1-5416bba33f9e.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by RChopin** [comment] 2022-10-15 17:48
same happened for me, but rebooting my device helped

**Comment by vamsee9** [comment] 2022-10-16 05:30
In which device are you facing ( e.g samsung m40 )

**Comment by Aunali321** [comment] 2022-10-16 06:18
An ad blocker or your dns is blocking it. Also dupe of #379

**Closed by Aunali321** 2022-10-16 06:18 UTC
Labels: bug
