### ISSUE TITLE
"Aberted" error when patching

### ISSUE THREAD

**Issue by batata004** [ReVanced/revanced-manager#1054] opened 2023-07-26 18:22 UTC
### Type

Error at runtime

### Bug description

When using the latest REVANCED MANAGER with the recommended youtube version on a non root smartphone trying to patch the DEFAULT options (7), I am getting this error:

```
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Custom branding
Applied Disable zoom haptics
Applied Enable debugging
Applied Hide cast button
Failed to apply Hide player overlay: Failed to resolve CreatePlayerOverviewFingerprint
Applied Premium heading
Applied Theme
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lhwXekifAG6zJiby99p-jg==/app.revanced.manager.flutter-9tyB3qyjLStCB512bsv7SQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1538776512, --version-name, 18.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4984822349169830234.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~lhwXekifAG6zJiby99p-jg==/app.revanced.manager.flutter-9tyB3qyjLStCB512bsv7SQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1538776512, --version-name, 18.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4984822349169830234.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BPSCRA/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Steps to reproduce

try to patch latest youtube with latest revanced manager

### Android version

latest

### Manager version

latest

### Target package name

latest

### Target package version.

latest

### Installation type

Non-root

### Patches selected.

latest

### Device logs (exported using Manager settings).

```shell
pasted above
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-07-27 08:46
Duplicate of #988

**Closed by TheAabedKhan** 2023-07-27 08:46 UTC
Labels: bug
