### ISSUE TITLE
bug: my device rebooted randomly

### ISSUE THREAD

**Issue by LostCat123** [revanced/revanced-manager#117] opened 2022-09-16 04:32 UTC
### Type

Other

### Branch

.

### Bug description

I successfully patches TikTok and YouTube, after a few minutes, my device just rebooted randomly and TikTok and YouTube were gone

### Steps to reproduce

Install them via root

### Relevant log output

```shell
--------- beginning of crash
09-16 11:31:56.912  8664  8664 E AndroidRuntime: FATAL EXCEPTION: main
09-16 11:31:56.912  8664  8664 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 8664
09-16 11:31:56.912  8664  8664 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5364)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5403)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2258)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7875)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8388)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5357)
09-16 11:31:56.912  8664  8664 E AndroidRuntime: 	... 13 more
```

### Solution

Idk

### Additional context

I'm rooted

**Comment by Aunali321** [comment] 2022-09-16 04:45
Can you try with 0.0.3 and see if you have the same issue?

**Comment by LostCat123** [comment] 2022-09-16 05:53
> Can you try with 0.0.3 and see if you have the same issue?

It doesn't have any issue

**Comment by Aunali321** [comment] 2022-09-16 05:58
@LostCat123 so it works in 0.0.3?

**Comment by LostCat123** [comment] 2022-09-16 11:41
> @LostCat123 so it works in 0.0.3?

Yes

**Comment by ponces** [comment] 2022-09-18 00:28
Are you able to reproduce this with latest version available?

**Comment by LostCat123** [comment] 2022-09-18 05:07
> Are you able to reproduce this with latest version available?

I'll try

**Comment by LostCat123** [comment] 2022-09-20 08:13
> Are you able to reproduce this with latest version available?

--------- beginning of main
09-20 16:11:23.659 18606 18606 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
09-20 16:11:23.662 18606 18606 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
09-20 16:11:23.680 18606 18606 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10304; state: ENABLED
09-20 16:11:23.769 18606 18606 V GraphicsEnvironment: ANGLE Developer option for 'app.revanced.manager.flutter' set to: 'default'
09-20 16:11:23.770 18606 18606 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
09-20 16:11:24.403 18606 18606 W manager.flutter: type=1400 audit(0.0:66271): avc: denied { read } for name="max_map_count" dev="proc" ino=7474007 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.revanced.manager.flutter
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: QUALCOMM build                   : b7b0bdba7c, I6815c23d01
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: Build Date                       : 07/26/22
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.40.05.00
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: Local Branch                     : 
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.12.C3.10.00.00.670.284
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: Remote Branch                    : NONE
09-20 16:11:24.422 18606 18606 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
09-20 16:11:24.423 18606 18606 I AdrenoGLES-0: Build Config                     : S P 8.0.12 AArch64
09-20 16:11:24.423 18606 18606 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-20 16:11:24.423 18606 18606 I AdrenoGLES-0: Driver Version                   : 642.0
09-20 16:11:24.438 18606 18606 I AdrenoGLES-0: PFP: 0x016ee18a, ME: 0x00000000
09-20 16:11:24.694 18606 18606 V AnimationHandler: enable
09-20 16:11:24.695 18606 18606 V AnimationHandler: animatorRequesters 0 = android.view.ViewRootImpl@9378f17
09-20 16:11:24.987 18606 18697 W SQLiteLog: (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
09-20 16:11:24.987 18606 18697 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-20 16:11:25.008 18606 18666 I flutter : dynamic_color: Core palette detected.
09-20 16:11:25.086 18606 18697 W SQLiteLog: (28) double-quoted string literal: "08F272E86A5BBA0E62C723AD1B16C63C"
09-20 16:11:25.086 18606 18697 W SQLiteLog: (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
09-20 16:11:25.096 18606 18668 I Gralloc4: Adding additional valid usage bits: 0x8202000
09-20 16:11:25.264 18606 18668 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=720x1600, requested_size=720x1600 buffer{size=720x1557 transform=0}
 
This happened on the newest version

**Comment by LostCat123** [comment] 2022-09-23 07:00
[revanced-manager_logcat_20220923072212592652.log](https://github.com/revanced/revanced-manager/files/9631318/revanced-manager_logcat_20220923072212592652.log)

**Comment by ILoveOpenSourceApplications** [comment] 2023-02-12 16:39
Looks like a very old bug related to a very old version of manager. So closing it.

**Closed by ILoveOpenSourceApplications** 2023-02-12 16:39 UTC
Labels: bug
