### ISSUE TITLE
Turn off list of all apps

### ISSUE THREAD

**Issue by TheSainEyereg** [revanced/revanced-manager#582] opened 2022-12-12 15:43 UTC
### Type

Functionality

### Issue

It's been loading for thousands of years and does nothing useful (no one needs A13 gestures), the only thing it adds is endless scrolling to the right app.

### Feature

Show only those applications for which the patches is available (as it was before 0.0.46).
Or just add switch that disables this annoying thing.

### Motivation

To make life easier for Revanced Manager users. This "feature" is really annoying

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2022-12-12 15:45
Dupe of #579

**Closed by Ushie** 2022-12-12 15:45 UTC
Labels: feature-request

**Comment by Ushie** [comment] 2022-12-12 15:47
no worries!
