### ISSUE TITLE
feat(installer): omit suggested version into log

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1552] opened 2023-12-05 05:52 UTC
This helps us quickly identify the suggested version without having to look up the compatibility list of this specific ReVanced Patches version.

### Current
```log
- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.202.0
Patches added: Bleep
Patches removed: Bloop
Options changed: Banana
```

### Suggested
```log
- Patch Info
App: com.google.android.youtube v18.45.43 (Suggested: vXX.XX.XX)
Patches version: v2.202.0
Patches added: Bleep
Patches removed: Bloop
Options changed: Banana
```

```log
- Patch Info
App: com.google.android.youtube
App version: vXX.XX.XX
App suggested version: vXX.XX.XX
Patches version: v2.202.0
Patches added: Bleep
Patches removed: Bloop
Options changed: Banana
```

**Comment by TheAabedKhan** [comment] 2023-12-05 06:01
Duplicate of #1550

**Closed** 2023-12-05 06:01 UTC
Labels: feature request
