### ISSUE TITLE
bug: Can't patch youtube music

### ISSUE THREAD

**Issue by KoleckOLP** [ReVanced/revanced-manager#1147] opened 2023-08-22 10:21 UTC
### Type

Error while running the manager

### Bug description

patching youtube music aborts

### Steps to reproduce

1. download youtube music, 
2. choose all patches except compact headder and the universal ones
3. patch

### Android version

13

### Manager version

1.8.0

### Target package name

com.google.android.apps.youtube.music

### Target package version.

6.15.51, 6.14.52, 6.14.50

### Installation type

Non-root

### Patches selected.

all patches except compact headder and the universal ones

### Device logs (exported using Manager settings).

```shell
https://pastebin.com/vJjDxZMy
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
https://pastebin.com/91qCW76m
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-08-22 13:53
Duplicate of #1130 and use YouTube Music v6.10.52 until the issue is resolved.

**Closed by TheAabedKhan** 2023-08-22 13:53 UTC
Labels: bug
