### ISSUE TITLE
BlankScreen

### ISSUE THREAD

**Issue by introversialscalpel** [revanced/revanced-manager#433] opened 2022-10-24 07:24 UTC
### Type

Error at runtime

### Bug description

Since the manager version 0.0.32, any of the manager app is stuck at the startup screen or the logo screen.

### Steps to reproduce

I installed the app, gave all the relevant permissions by going into the settings, and then opened the app

### Android version

Android 12

### Manager version

v0.0.36

### Target package name

YouTube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

All except Custom Branding and debug

### Device logs (exported using Manager settings).

```shell
Can't open the app even to check the logs.
```

### Screenshots or videos

![Screenshot_20221024-124138](https://user-images.githubusercontent.com/102604664/197469753-fb356109-52ba-4d3d-bc41-b6130d4bcce0.jpg)

### Additional context

Installed the app via SAI app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-24 07:44
Dupe of #379

**Closed by Aunali321** 2022-10-24 07:44 UTC
Labels: bug
