### ISSUE TITLE
bug: Manager doesn't open with adblock enabled

### ISSUE THREAD

**Issue by P13rlU** [revanced/revanced-manager#441] opened 2022-10-26 07:47 UTC
### Type

Error at runtime

### Bug description

the manager simply does not start if you enable an adblock on your phone.
this happens in every version between 0.0.30 and 0.0.36 (latest at the time of writing the issue).

### Steps to reproduce

Step 1. enable adblock
Step 2. download and install any version between 0.0.30 and 0.0.36
Step 3. open the manager and enjoy the stuck logo forever

### Android version

12L (i think this is the reason it doesn't work, because even disabling the adblock does not fix the problem

### Manager version

every version between 0.0.30 and 0.0.36

### Target package name

none

### Target package version.

none

### Installation type

Root

### Patches selected.

none

### Device logs (exported using Manager settings).

```shell
can't upload any log because the manager doesn't start
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
can't upload any log because the manager doesn't start
```

### Screenshots or videos

![Screenshot_20221026-094131_ReVanced Manager](https://user-images.githubusercontent.com/67976483/197965871-c8fad38c-c6a9-47fc-93da-2adf607d7135.png)

### Solution

Disable any adblock that you have on your phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by P13rlU** [comment] 2022-10-26 08:01
EDIT: it's not the adblock, i think it's the android version, because i have android 12L and doesn't work, but with my friend's phone which has normal android 12 works flawlessly

**Comment by Ushie** [comment] 2022-10-26 08:04
Hey! this is due to our releases API domain is flagged as a "Newly Registered Domain (NRD)" by various sources, we're in the process of moving to api.revanced.app once the maintainer is free

**Comment by ExperiencersInternational** [comment] 2022-10-26 22:38
Can't reproduce with using AdGuard DNS.

**Comment by Neon329** [comment] 2022-10-28 03:27
Facing this issue with AdGuard for Android enabled on Android 12, OnePlus Nord 2. The ReVanced Manager simply doesn't open when AdGuard is enabled. Can provide any logs if needed.

**Comment by ExperiencersInternational** [comment] 2022-10-28 09:33
> Facing this issue with AdGuard for Android enabled on Android 12, OnePlus Nord 2. The ReVanced Manager simply doesn't open when AdGuard is enabled. Can provide any logs if needed.

I'm using AdGuard DNS and the ReVanced manager has always opened properly, and seems to be working fine (at least for launcher updates, I don't think I'm getting patcher updates).

![Screenshot_2022-10-28-10-32-33-886_com android settings](https://user-images.githubusercontent.com/56035537/198555433-62a1a9c3-33b5-4057-a1fa-9c024d1c195a.jpg)

**Comment by eNV25** [comment] 2022-10-30 17:13
> Hey! this is due to our releases API domain is flagged as a "Newly Registered Domain (NRD)" by various sources, we're in the process of moving to api.revanced.app once the maintainer is free

What's the actual domain that is used? I want to whitelist it.

**Comment by Ushie** [comment] 2022-10-30 17:49
> > Hey! this is due to our releases API domain is flagged as a "Newly Registered Domain (NRD)" by various sources, we're in the process of moving to api.revanced.app once the maintainer is free
> 
> What's the actual domain that is used? I want to whitelist it.

https://rvcd.win/ (the subdomain is https://releases.rvcd.win/)

**Closed** 2022-11-01 08:22 UTC
Labels: bug
