### ISSUE TITLE
bug: <title>Error when trying to download Youtube Music

### ISSUE THREAD

**Issue by OmniTheGodKing** [ReVanced/revanced-manager#1097] opened 2023-08-06 10:43 UTC
### Type

Error while running the manager

### Bug description

attempted to patch YouTube Music and was presented with an error and a aborted message. 

### Steps to reproduce

1. download latest Manager
2. attempt to patch Youtube music using the patcher
3. wait
4. profit

### Android version

Android 13

### Manager version

1.6.1

### Target package name

Youtube Music

### Target package version.

v6. 13.52

### Installation type

Non-root

### Patches selected.

Default.

Background Play
Bypass Certificate checks
Codecs Unlock
Exclusive Audio Playback
Hide Get Premium
Minimized Playback Music
Music Video Ads
Upgrade Button Remover
Vanced microG Support

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vmZZKR-b2GlEmAj4FCEW5A==/app.revanced.manager.flutter-vrH7jd5XYTZgqGIQj-WGGA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6503119897212373958.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vmZZKR-b2GlEmAj4FCEW5A==/app.revanced.manager.flutter-vrH7jd5XYTZgqGIQj-WGGA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6503119897212373958.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vmZZKR-b2GlEmAj4FCEW5A==/app.revanced.manager.flutter-vrH7jd5XYTZgqGIQj-WGGA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6503119897212373958.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vmZZKR-b2GlEmAj4FCEW5A==/app.revanced.manager.flutter-vrH7jd5XYTZgqGIQj-WGGA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6503119897212373958.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-MQXCUZ/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by OmniTheGodKing** [comment] 2023-08-06 10:45
I am also unable to export Apk as the file appears to be empty

**Comment by ILoveOpenSourceApplications** [comment] 2023-08-06 14:02
> I am also unable to export Apk as the file appears to be empty

This is an unrelated issue. Your issue is related to #1084 .

**Comment by ILoveOpenSourceApplications** [comment] 2023-08-06 14:05
Actually this a duplicate of [#206](https://github.com/ReVanced/revanced-patcher/issues/206) . Please stick with 6.10.XX or below versions for the time being.

**Closed** 2023-08-06 14:09 UTC
Labels: bug
