### ISSUE TITLE
What App / what Version? We need some ui/ux Love too!

### ISSUE THREAD

**Issue by 101Gaming** [revanced/revanced-manager#581] opened 2022-12-12 10:25 UTC
### Type

Functionality

### Issue

the Implementation of #577 made the user experience worse. Even than before. 
Now He Sees, unser Patches, every installed APK without knowing If its a Major Featured App or Just a minor one. The loading of the list takes a consideable amount of time aswell. User wont know which is a full Featured APK and which Version is recommended. Without  checking a previously Downloaded Version. The regular User wont use github and certainly wont know about any of revanced Featured Apps!

### Feature

- Create a seperate Window for shared Updates.
- list in a primary Window every Major Featured APK. With recommended Version, a Status flag Like "installed" "Patched" "notfound" whatever as an indicator for the User to Test some Shit. There Version Number links directly to APKmirror to be more convinient.

### Motivation

Some simple uiux basics. Many Users dont know about Supported Apps, new Features and so on. They dont use GitHub at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2022-12-12 10:28
Dupe of #579

**Closed by Ushie** 2022-12-12 10:28 UTC
Labels: feature-request

**Comment by 101Gaming** [comment] 2022-12-12 10:34
This is a diffrent approach to a diffrent issue with the Manager. Not related to #579 beides the loading Point.

**Comment by Ushie** [comment] 2022-12-12 14:47
> This is a diffrent approach to a diffrent issue with the Manager. Not related to #579 besides the loading issue of #579.

Okay, 
> There Version Number links directly to APKmirror to be more convinient.

Dupe of #495 #508 #436 #289 #125 #12 

As for the displaying recommended version on AppCards in AppSelector, and "status flags", open individual new issues please
