### ISSUE TITLE
feat: Add patches version in App info

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#1515] opened 2023-11-22 16:11 UTC
### Feature description

In App info add the version of patches installed.
![Screenshot_20231121_201400_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/127908708/a482a1a8-3d97-4b7d-bfcf-284325bf4218)

### Motivation

It would be really useful and a quick way to check and know which version is currently installed.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment] 2023-11-22 16:23
Duplicate of #995

**Closed by TheAabedKhan** 2023-11-22 16:23 UTC
Labels: feature request
