### ISSUE TITLE
bug: [HIGH-PRIO] Usage of broken `permission_handler` plugin in Manager causing a crash

### ISSUE THREAD

**Issue by Sculas** [revanced/revanced-manager#141] opened 2022-09-16 18:24 UTC
### Type

Error at runtime

### Branch

Flutter

### Bug description

Introduced in `0.0.7`, a plugin called `permissions_handler` was added to handle permissions.
Unfortunately, this plugin seems to be broken, because it crashes the Manager with the stack trace below.

### Steps to reproduce

Unknown.

### Relevant log output

```shell
--------- beginning of crash
09-15 17:28:33.054 22195 22195 E AndroidRuntime: FATAL EXCEPTION: main
09-15 17:28:33.054 22195 22195 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 22195
09-15 17:28:33.054 22195 22195 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5541)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5580)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2346)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:238)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:349)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8241)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8487)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5534)
09-15 17:28:33.054 22195 22195 E AndroidRuntime: 	... 13 more
```

**Comment by oSumAtrIX** [comment] 2022-09-16 18:31
Btw, for priorities tags should be created, that way issues can be prioritized easily.

**Comment by Sculas** [comment] 2022-09-16 19:48
Of course, but it doesn't exist yet.

**Comment by ponces** [comment] 2022-09-18 02:46
@Lucaskyy check the file I sent on Discord to test a fix on this topic as I can't reproduce it... Thanks!

**Comment by ponces** [comment] 2022-09-20 02:08
Fixed on https://github.com/revanced/revanced-manager/commit/9c5b0b9c14f382274909c776a2fa88028ab3c25b.
Closed.

**Closed by ponces** 2022-09-20 02:08 UTC
Labels: bug
