### ISSUE TITLE
bug: Tiktok can not patch

### ISSUE THREAD

**Issue by khaisilk1910** [ReVanced/revanced-manager#2252] opened 2024-10-09 06:05 UTC
### Bug description

bug: Tiktok can not patch

### Version of ReVanced Manager and version & name of app you are patching

bug: Tiktok can not patch

### Installation method

None

### ReVanced Manager logs

bug: Tiktok can not patch

### Patch logs

- Device Info
ReVanced Manager: 1.22.0
Model: 21121210G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.zhiliaoapp.musically v36.5.4 (Suggested: 36.5.4)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 22 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 5212016 free bytes and 5089KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(Unknown Source:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedFieldReference.getName(Unknown Source:30)
	at com.android.tools.smali.dexlib2.base.reference.BaseFieldReference.hashCode(Unknown Source:10)
	at java.util.HashMap.hash(HashMap.java:337)
	at java.util.HashMap.put(HashMap.java:617)
	at com.android.tools.smali.dexlib2.writer.pool.FieldPool.intern(Unknown Source:7)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.internReference(Unknown Source:75)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.internCode(Unknown Source:42)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.intern(Unknown Source:219)
	at com.android.tools.smali.dexlib2.writer.pool.DexPool.internClass(Unknown Source:4)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:27)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by validcube** [comment] 2024-10-09 08:52
👋 Hello, @khaisilk1910!

Thanks for filing this issue, but however, this issue is a duplicate of 
* #1454 #2126 and many others

Your issue has been updated with a list of acknowledgements that haven't been met.

**Closed by validcube** 2024-10-09 08:52 UTC
Labels: Bug report
