### ISSUE TITLE
feat: auto dark mode

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-manager#75] opened 2022-09-14 21:29 UTC
### Type

Cosmetic

### Branch

Flutter

### Issue

At the moment dark mode doesn't follow global tint settings.

### Feature

Apply a code to automatically set app theme based on Android global settings.

### Motivation

To keep system consistency.

**Comment by Aunali321** [comment] 2022-09-14 21:34
duplicate of #70.

**Closed by Aunali321** 2022-09-14 21:34 UTC
Labels: feature-request
