### ISSUE TITLE
Manger couldn't connect to internet, Freezing at every startup 

### ISSUE THREAD

**Issue by ZekoRonaldo** [revanced/revanced-manager#301] opened 2022-09-25 19:04 UTC
### Type

Other

### Bug description

The manager freeze at every startup for 5-10 seconds like it trying to connect to internet and then opens normally, after opening can't load status for Manger and patcher can't load apps, patches or anything the completely can't establish an internet connection 

### Steps to reproduce

I tried many versions, even the initial version which was working good for me before but not the same ROM 

### Android version

A 12, MIUI 13.0.6 China based 

### Manager version

Initial version
0.21
0.24
Other versions cannot remember 

### Target package name

Manger can't load any package to patch 

### Target package version.

Manger can't load any package to patch 

### Installation type

Root

### Patches selected.

Manger can't load any package to patch 

### Device logs (exported using Manager settings).

```shell
NA
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Na
```

### Screenshots or videos

![Screenshot_2022-09-25-20-06-09-654_com miui securitycenter-edit](https://user-images.githubusercontent.com/63168860/192160827-6c8f43e8-7909-4c70-9ffd-ab878533da39.jpg)

### Solution

NA

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-09-26 03:12
Reinstall manager and dupe of #292.

**Closed by Aunali321** 2022-09-26 03:12 UTC
Labels: bug

**Comment by ZekoRonaldo** [comment] 2022-09-26 13:03
I already did that, Reinstall the Manger several times, different versions, give all possible permissions and the same problem still exists,
