### ISSUE TITLE
bug: Older android phones can't compile.

### ISSUE THREAD

**Issue by anoraktrend** [revanced/revanced-manager#556] opened 2022-11-30 22:52 UTC
### Type

Error while running the manager

### Bug description

Crash at package recompile time

### Steps to reproduce

Attempt to build youtube with recommended patches with the specified android version.

### Android version

Android 8.1, a32 (32bit userland on 64bit CPU).

### Manager version

All including 0.43

### Target package name

YouTube

### Target package version.

Recommended

### Installation type

Non-root

### Patches selected.

Recommended 

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied general-ads
Applied video-ads
Applied downloads
Applied seekbar-tapping
Applied swipe-controls
Applied disable-auto-captions
Applied hide-autoplay-button
Applied premium-heading
Applied custom-branding
Applied hide-video-buttons
Applied hide-cast-button
Applied comments
Applied disable-fullscreen-panels
Applied hide-album-cards
Applied hide-artist-card
Applied hide-captions-button
Applied hide-crowdfunding-box
Applied hide-endscreen-cards
Applied hide-info-cards
Applied hide-my-mix
Applied hide-time-and-seekbar
Applied old-quality-layout
Applied hide-email-address
Applied hide-create-button
Applied hide-shorts-button
Applied remove-player-button-background
Applied disable-auto-player-popup-panels
Applied return-youtube-dislike
Applied sponsorblock
Applied disable-startup-shorts-player
Applied tablet-mini-player
Applied hide-watch-in-vr
Applied hide-watermark
Applied enable-wide-searchbar
Applied always-autorepeat
Applied client-spoof
Applied debugging
Applied hdr-auto-brightness
Applied microg-support
Applied minimized-playback
Applied open-links-directly
Applied settings
Applied remember-video-quality
Applied custom-video-speed
Applied custom-video-buffer
Applied disable-zoom-haptics
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-oZO9fqLu5gBI9K2cpk_lvg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4420572510850873785.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:494)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:148)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:764)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-oZO9fqLu5gBI9K2cpk_lvg==/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1532749248, --version-name, 17.45.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4420572510850873785.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IQLWOP/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:490)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-12-01 05:14
Dupe of #268.

**Closed by Aunali321** 2022-12-01 05:14 UTC
Labels: bug
