### ISSUE TITLE
Error during compilation of YouTube music.

### ISSUE THREAD

**Issue by dickta** [ReVanced/revanced-manager#1091] opened 2023-08-05 16:27 UTC
### Type

Error while running the manager

### Bug description

Error on compilation of YouTube Music after successfully applied patches. 

### Steps to reproduce

Step 1: download YouTube music 6.13.52 from APK mirror
Step 2: open the APK from the patching menu
Step 3: apply any patch you want
Step 4: compilation error

### Android version

13 MIUI

### Manager version

1.6.1

### Target package name

com.google.android.apps.youtube.music

### Target package version.

6.13.52-61352240_minAPI21(arm64-v8a)

### Installation type

Non-root

### Patches selected.

![Screenshot_2023-08-05-18-15-25-112_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/46004216/fba14d68-dcc6-41f4-b567-c1a2ae45d057)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~NxQJtHIwdh-rQ-Ge_oeNMA==/app.revanced.manager.flutter-_cPRFdnlzMv5PmYdVtDZAw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6269271246691134907.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:276)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~NxQJtHIwdh-rQ-Ge_oeNMA==/app.revanced.manager.flutter-_cPRFdnlzMv5PmYdVtDZAw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61352240, --version-name, 6.13.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6269271246691134907.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-TYTLAB/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/46004216/14d79d9c-1bfb-4e59-9547-dfc5c2d002a0

### Acknowledgments

- [ ] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [x] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-08-05 16:58
Duplicate of #988

**Closed by TheAabedKhan** 2023-08-05 16:58 UTC
Labels: bug

**Comment by ILoveOpenSourceApplications** [comment] 2023-08-05 18:15
Actually this a duplicate of [#206](https://github.com/ReVanced/revanced-patcher/issues/206). Please stick with 6.10.XX or below versions for the time being.
