### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by tryigit** [revanced/revanced-manager#176] opened 2022-09-17 20:21 UTC
### Type

Error at runtime

### Branch

Flutter

### Bug description

Creating an application patch

### Steps to reproduce

1. Open app.
2. Create YouTube patch.

### Relevant log output

```shell
kotlin.io.NoSuchFileException: /data/local/tmp/revanced-manager/com.reddit.frontpage/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:125)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by pietryszak** [comment] 2022-09-17 20:28
YT and reddit crash on 0.0.8 and 0.0.9.
Duplicate https://github.com/revanced/revanced-manager/issues/172

**Comment by Alprnn357** [comment] 2022-09-17 20:32
According to crash log, manager doesn't copy the file before patching to that dir:
/data/local/tmp/revanced-manager/com.reddit.frontpage/
so it can't find that apk file and then crashes.
is this 0.0.9 version? @tryigit

**Comment by tryigit** [comment] 2022-09-17 20:33
> According to crash log, manager doesn't copy the file to that dir before patching:
> /data/local/tmp/revanced-manager/com.reddit.frontpage/
> so it can't find that apk file and then crashes.
> is this 0.0.9 version? @tryigit 

Yes this version.

**Comment by Alprnn357** [comment] 2022-09-17 20:39
but why is it checks reddit package name intstead of youtube?

**Comment by iamflorencejay** [comment] 2022-09-18 00:34
here is my crash when it's patching:

```
time: 1663461107222
msg: java.util.NoSuchElementException: Array is empty.
stacktrace: java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1013)
```

**Comment by ponces** [comment] 2022-09-18 02:59
Duplicate of https://github.com/revanced/revanced-manager/issues/172.
Closed.

**Closed by ponces** 2022-09-18 02:59 UTC
Labels: bug
