### ISSUE TITLE
bug: Unable to update Youtube/YT Music apps straight from ReVanced Manager, need to manually delete files in "/data/adb/" (root)

### ISSUE THREAD

**Issue by MSTRKKRFT** [ReVanced/revanced-manager#952] opened 2023-06-16 08:44 UTC
### Type

Other

### Bug description

Hello, 

I'm on Pixel 7 Pro (Android 13 May 2023 update), using last version of ReVanced Manager (root method, without Vanced MicroG) 

I can't update my YouTube / YT Music straight from ReVanced Manager. If I download the apk from apkmirror, patch it with the manager, and install it above the precedent patched version of YouTube / YT Music : it works until I reboot the phone. As soon as I reboot the phone, the apps are crashing at launch and are unusable. 

I know there is already a thread here about that, but it's marked as "close", but it isn't as the problem is still here, that's why I'm opening a new issue here. 

To fix that issue I found this guide from Retrial on XDA : https://forum.xda-developers.com/t/app-8-0-guides-revanced-revanced-extended.4523967/

So, what I need to do to update my apps is : 

1. Uninstall YouTube / YT Music app updates from the App Manager in Android system parameters. 
2. Use root browser to delete all the files in "/data/adb/post-fs-data.d" & "/data/adb/service.d". The post from XDA suggests to also delete files inside "/data/local/tmp/revanced-manager" but it's not needed in my case. 
3. Reboot the phone
4. Install updated YouTube / YT Music APKs downloaded from apkmirror
5. Patch the apps in ReVanced Manager
6. Install as root

Is it possible to implement that process directly inside the Manager ? The reboot is crucial to make everything work in my case, so even adding a clean manager files/reboot phone tool inside the manager would make it a bit more user-friendly. 

### Steps to reproduce

1. Uninstall YouTube / YT Music app updates from the App Manager in Android system parameters. 
2. Install updated YouTube / YT Music APKs downloaded from apkmirror
3. Patch the apps in ReVanced Manager
4. Install as root
5. Reboot the phone 
6. The apps are crashing at start 

### Android version

Android 13 May 2023 Update 

### Manager version

v1.3.5

### Target package name

com.google.android.youtube
com.google.android.apps.youtube.music

### Target package version.

Youtube : 18.19.35
Youtube Music : 5.39.52

### Installation type

Root

### Patches selected.

YouTube : client spoof, copy video url, hide ads, minimized playback, old quality layout, open links externally, premium heading, remember video quality, sponsorblock, swipe controls, video ads, external downloads, remove screenshot/screen capture restriction
YT Music : background play, bypass certificate checks, codecs unlock, exclusive audio playback, hide get premium, minimized playback music, music video ads, upgrade button remover, remove screenshot/screen capture restriction

### Device logs (exported using Manager settings).

```shell
Nothing relevant as I get no errors whatsoever during patching/installing.
```

### Solution

1. Uninstall YouTube / YT Music app updates from the App Manager in Android system parameters. 
2. Use root browser to delete all the files in "/data/adb/post-fs-data.d" & "/data/adb/service.d". The post from XDA suggests to also delete files inside "/data/local/tmp/revanced-manager" but it's not needed in my case. 
3. Reboot the phone
4. Install updated YouTube / YT Music APKs downloaded from apkmirror
5. Patch the apps in ReVanced Manager
6. Install as root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by caliban511** [comment] 2023-07-16 22:25
Thank you, my friend. You're right.

**Comment by oSumAtrIX** [comment] 2023-07-29 20:39
@TheAabedKhan if this has been fixed in dev, you can link issues to auto-close:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/3bc1fa0c-7e1c-42df-8413-a08d6f383611)

**Comment by TheAabedKhan** [comment] 2023-07-29 20:46
Oh, no! Because of the title, I couldn’t know that the #975 is the duplicate of this issue.

**Closed** 2023-08-02 23:20 UTC
Labels: bug
