### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by someone5678** [revanced/revanced-manager#126] opened 2022-09-16 12:32 UTC
### Type

Error while running the manager

### Branch

flutter

### Bug description

APK file can be selected but Patcher shows No application selected.

### Steps to reproduce

Patcher -> Select application -> Storage -> Select APK

### Relevant log output

```shell
N/A Because there's no such logcat found...
```

**Comment by Aunali321** [comment] 2022-09-16 12:33
duplicate of #93

**Closed by Aunali321** 2022-09-16 12:33 UTC
Labels: bug
