### ISSUE TITLE
bug: Can't select application

### ISSUE THREAD

**Issue by rapdodge** [revanced/revanced-manager#189] opened 2022-09-18 08:56 UTC
### Type

Other

### Branch

Releases

### Bug description

When selecting application on Patcher menu, it can't be selected, just return blank

### Steps to reproduce

1. Open ReVanced Manager
2. Select application
3. Click storage
4. Select the APK files

### Relevant log output

```shell
--------- beginning of system
09-18 15:42:27.783 13340 13340 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:44:18.482 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:44:18.574 27235 27235 I SystemConfig: Non-xml file /system/etc/permissions/pms_sysapp_removable_system_list.txt in /system/etc/permissions directory, ignoring
09-18 15:44:18.610 27235 27235 I SystemConfig: Non-xml file /system/etc/permissions/pms_sysapp_removable_vendor_list.txt in /system/etc/permissions directory, ignoring
09-18 15:44:18.756 27235 27235 W SystemConfig: No directory /product_services/etc/sysconfig, skipping
09-18 15:44:18.757 27235 27235 W SystemConfig: No directory /product_services/etc/permissions, skipping
09-18 15:44:24.365 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:44:46.737 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:45:15.233 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:49:10.342 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
--------- beginning of main
09-18 15:49:16.779 27235 27254 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
09-18 15:49:18.547 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:18.560 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:18.575 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:24.285 27235 27235 W System.err: java.io.IOException: Cannot run program "su": error=13, Permission denied
09-18 15:49:24.292 27235 27235 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:48)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:40)
09-18 15:49:24.292 27235 27235 W System.err: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
09-18 15:49:24.292 27235 27235 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
09-18 15:49:24.292 27235 27235 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
09-18 15:49:24.292 27235 27235 W System.err: 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
09-18 15:49:24.292 27235 27235 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
09-18 15:49:24.292 27235 27235 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-18 15:49:24.292 27235 27235 W System.err: 	at android.os.Looper.loop(Looper.java:214)
09-18 15:49:24.292 27235 27235 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7386)
09-18 15:49:24.292 27235 27235 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-18 15:49:24.292 27235 27235 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
09-18 15:49:24.294 27235 27235 W System.err: Caused by: java.io.IOException: error=13, Permission denied
09-18 15:49:24.294 27235 27235 W System.err: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
09-18 15:49:24.294 27235 27235 W System.err: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
09-18 15:49:24.294 27235 27235 W System.err: 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
09-18 15:49:24.294 27235 27235 W System.err: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
09-18 15:49:24.294 27235 27235 W System.err: 	... 18 more
09-18 15:49:27.162 27235 27254 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
09-18 15:49:30.674 27235 30646 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A15
09-18 15:49:30.694 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:30.699 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:30.706 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:30.770 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:49:30.815 27235 27259 I flutter : type 'Null' is not a subtype of type 'String' in type cast
09-18 15:49:35.368 27235 27254 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
09-18 15:49:37.788 27235 30676 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A15
09-18 15:49:37.809 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:37.813 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:37.817 27235 27235 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
09-18 15:49:37.878 27235 27235 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/YouTube_17.36.37_apkcombo.com.apk Binary XML file line #41
09-18 15:49:37.900 27235 27259 I flutter : type 'Null' is not a subtype of type 'String' in type cast
```

### Screenshots or videos

https://user-images.githubusercontent.com/33513626/190894063-5e53ab45-b2b8-4892-8bd7-e169f105b8d8.mp4

**Comment by Aunali321** [comment] 2022-09-18 09:05
Duplicate of #93.

**Closed by Aunali321** 2022-09-18 09:05 UTC
Labels: bug
