### ISSUE TITLE
bug: Revanced manager 0.30 doesnt open

### ISSUE THREAD

**Issue by keatit71** [revanced/revanced-manager#374] opened 2022-10-09 05:47 UTC
### Type

Error at runtime

### Bug description

I updated to revanced manager 0.30 and it wouldnt load

### Steps to reproduce

Download version 0.30 or update to it
Try to open it

### Android version

Android 12
OneUI 4.1

### Manager version

0.30

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment] 2022-10-09 07:05
Try disabling vpn or use official google dns. Make sure your ad blocker is not blocking the manager. If that doesn't, redownload the manager apk and install.

**Comment by keatit71** [comment] 2022-10-09 09:33
I already tried reinstalling it and the vpn or dns didnt work

**Comment by JustEbu** [comment] 2022-10-09 17:04
I had the same issue. I'm using "NextDNS" with "Block Newly Registered Domains (NRDs)" enabled and that was blocking the new API url for Revanced Manager "releases.rvcd.win". Can you try to somehow allow/not block "releases.rvcd.win"?

**Comment by prat89** [comment] 2022-10-09 20:19
I'm having the same issue

**Comment by kevin01523** [comment] 2022-10-09 20:37
same i think it depends on a per device basis my huawei tablet won't load the patches and stuck to updating

**Comment by BubuXP** [comment] 2022-10-09 21:16
> same i think it depends on a per device basis my huawei tablet won't load the patches and stuck to updating

My device is Mi 9T with custom Android 12 vanilla ROM (without Google services installed) from April 2022.

In Dashboard, under the Updates section, Patcher and Manager remains in "Loading..." state, not loading any patch. It's like the app cannot access the internet, and watching the 0.0.30 changelog I see HTTP/3 support has been added. Could H3 be the cause (or something related to it)?
For me .29 works fine, even when changing the API URL with the one from the .30 default setting, while the .30 version doesn't work even with the old API URL (just to exclude an URL problem).

**Comment by kevin01523** [comment] 2022-10-10 09:51
from the logs it has google services errors so ot maybe due to that

**Comment by Aunali321** [comment] 2022-10-16 06:21
Closing in favour of #379.

**Closed by Aunali321** 2022-10-16 06:21 UTC
Labels: bug
