### ISSUE TITLE
bug: App crashes on startup

### ISSUE THREAD

**Issue by koopa990** [ReVanced/revanced-manager#1351] opened 2023-10-09 14:24 UTC
### Bug description

This strange crash recently happens. When I first installed the app last week or so, I never encountered the problem.

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager version 1.10.3

### Installation type

Non-root

### Device logs

```shell
Unable to get logs because of persistent crash.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment] 2023-10-09 14:36
Attach logs using logcat.

**Comment by koopa990** [comment] 2023-10-09 14:56
> Attach logs using logcat.

Is that another app?

**Comment by oSumAtrIX** [comment] 2023-10-09 14:57
https://developer.android.com/tools/logcat

**Comment by fessmm** [comment] 2023-10-09 15:04
Hey @koopa990 just install the latest version manually. It will fix it. I had this crash too.

**Comment by KobeW50** [comment] 2023-10-09 16:26
This is a dupe of https://github.com/ReVanced/revanced-manager/issues/1330 and https://github.com/ReVanced/revanced-manager/issues/1339

**Closed** 2023-10-09 16:38 UTC
Labels: bug
