### ISSUE TITLE
feat: patch "x" app in the backround

### ISSUE THREAD

**Issue by XxFrAnCoGoLxX** [ReVanced/revanced-manager#1134] opened 2023-08-15 01:47 UTC
### Type

Functionality

### Issue

when patching youtube and using other apps, revanced manager gets suspended/interrupted after a while

### Feature

add an option to allow backround patching

### Motivation

the patching process takes a lot of time, and it is annoying not being able use the phone in the meantime

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by TheAabedKhan** [comment] 2023-08-15 03:29
Duplicate of #684

**Closed by TheAabedKhan** 2023-08-15 03:29 UTC
Labels: feature-request
