### ISSUE TITLE
Stuck at initializing screen

### ISSUE THREAD

**Issue by Tanzeel159** [ReVanced/revanced-manager#1139] opened 2023-08-17 14:30 UTC
### Type

Error while running the manager

### Bug description

Whenever I try to patch any apk, I am stuck at initializing screen.

### Steps to reproduce

1) Download any app apk
2) Try to patch the apk from local storage option

### Android version

Android 13
OS : Funtouch OS 13 
Device : IQOO Neo 7 Pro

### Manager version

1.8.0

### Target package name

com.google.android.apps.youtube.music_6.15.51-61551240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk (Youtube-Music) and any other apk

### Target package version.

6.15.51

### Installation type

Non-root

### Patches selected.

Selected all the default patches for the apk

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
08-17 18:29:44.698 26921 26921 E AndroidRuntime: FATAL EXCEPTION: main
08-17 18:29:44.698 26921 26921 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 26921
08-17 18:29:44.698 26921 26921 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5825)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5864)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2631)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:223)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:324)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8679)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:9154)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5818)
08-17 18:29:44.698 26921 26921 E AndroidRuntime: 	... 13 more
--------- beginning of system
08-17 18:29:59.161 27509 27509 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/revanced-manager-v1.8.0.apk Binary XML file line #29
08-17 18:30:10.260 27509 27509 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_6.15.51-61551240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #133
08-17 18:39:26.715  5084  5084 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/revanced-manager-v1.8.0.apk Binary XML file line #29
08-17 18:39:36.728  5084  5084 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_6.15.51-61551240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #133
08-17 18:40:12.209  6920  6920 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_6.15.51-61551240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #133
08-17 18:45:09.360  9173  9173 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_6.15.51-61551240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #133
--------- beginning of main
08-17 19:49:43.783 27943 27943 I manager.flutter: Using CollectorTypeCC GC.
08-17 19:49:43.786 27943 27943 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: QUALCOMM build                   : ee4b625, I41c6f366e1
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Build Date                       : 02/16/23
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV************
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Local Branch                     : 
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Remote Branch                    : 
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Remote Branch                    : 
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Reconstruct Branch               : 
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Build Config                     : S P 12.1.1 AArch64
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-17 19:49:43.907 27943 27943 I AdrenoGLES-0: Driver Version                   : 0615.60
08-17 19:49:43.909 27943 27943 I AdrenoGLES-0: PFP: 0x01730147, ME: 0x00000000
08-17 19:49:43.970 27943 27943 E BLASTBufferQueue: Cannot find perfservice
08-17 19:49:44.314 27943 27943 I Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
08-17 19:49:44.328 27943 27972 I flutter : dynamic_color: Core palette detected.
08-17 19:49:44.360 27943 27973 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2334 transform=0}
08-17 19:49:44.372 27943 27966 W Parcel  : Expecting binder but got null!
08-17 19:49:46.522 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.522 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.545 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.545 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.572 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.572 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.617 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.617 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.635 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.635 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.648 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:46.648 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:49.405 27943 27954 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
08-17 19:49:52.497 27943 27943 I InstallPlugin: handleActivityResult(9714,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-17 19:49:52.497 27943 28904 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A1000057179
08-17 19:49:52.683 27943 27943 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.apps.youtube.music_6.14.50-61450240_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #133
08-17 19:49:52.694 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:52.694 27943 27943 W libc    : Access denied finding property "vendor.vivo.imageencoder.dump"
08-17 19:49:54.631 27943 27956 W System  : A resource failed to call close. 
08-17 19:49:54.732 27943 27972 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
08-17 19:49:54.732 27943 27972 E flutter : #0      PatcherAPI.runPatcher (package:revanced_manager/services/patcher_api.dart:194)
08-17 19:49:54.732 27943 27972 E flutter : <asynchronous suspension>
08-17 19:49:54.732 27943 27972 E flutter : #1      InstallerViewModel.runPatcher (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:136)
08-17 19:49:54.732 27943 27972 E flutter : <asynchronous suspension>
08-17 19:49:54.732 27943 27972 E flutter : #2      InstallerViewModel.initialize (package:revanced_manager/ui/views/installer/installer_viewmodel.dart:69)
08-17 19:49:54.732 27943 27972 E flutter : <asynchronous suspension>
08-17 19:49:54.732 27943 27972 E flutter : 
08-17 19:52:04.663 30106 30106 I manager.flutter: Using CollectorTypeCC GC.
08-17 19:52:04.666 30106 30106 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: QUALCOMM build                   : ee4b625, I41c6f366e1
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Build Date                       : 02/16/23
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV************
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Local Branch                     : 
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Remote Branch                    : 
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Remote Branch                    : 
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Reconstruct Branch               : 
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Build Config                     : S P 12.1.1 AArch64
08-17 19:52:04.789 30106 30106 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-17 19:52:04.790 30106 30106 I AdrenoGLES-0: Driver Version                   : 0615.60
08-17 19:52:04.792 30106 30106 I AdrenoGLES-0: PFP: 0x01730147, ME: 0x00000000
08-17 19:52:04.853 30106 30106 E BLASTBufferQueue: Cannot find perfservice
08-17 19:52:05.191 30106 30106 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
08-17 19:52:05.205 30106 30136 I flutter : dynamic_color: Core palette detected.
08-17 19:52:05.241 30106 30137 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:0) rejecting buffer:active_size=1080x2400, requested_size=1080x2400 buffer{size=1080x2334 transform=0}
08-17 19:52:05.249 30106 30128 W Parcel  : Expecting binder but got null!
```

### Screenshots or video

![mbfj3kak3oib1](https://github.com/ReVanced/revanced-manager/assets/20295349/0afae563-0edd-4ff2-b2f4-579365a03771)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by xDARKxDEVILx** [comment] 2023-08-17 17:47
Use version 6.10.52

**Comment by KobeW50** [comment] 2023-08-17 18:36
Also try resetting the Sources from the Manager settings.

**Comment by Tanzeel159** [comment] 2023-08-17 18:41
If you guys checked the log file which I have uploaded, I think this issue is related to the device
specifically this error 

Access denied finding property "vendor.vivo.imageencoder.dump"
When I try patching any app, the screen is stuck at initializing as mentioned, in background it's expecting binder but unable to acquire it. I don't have much idea about it, but I didn't face this issue on my last phone(Oneplus 7T).

**Comment by ILoveOpenSourceApplications** [comment] 2023-08-18 03:44
This issue occurs due to the manager being unable to connect to the network. Mostly this is caused by the user being connected to a VPN or is using some sort of ad blocker.

**Comment by ILoveOpenSourceApplications** [comment] 2023-08-18 03:47
Duplicate of #483.

**Closed by ILoveOpenSourceApplications** 2023-08-18 03:47 UTC
Labels: bug

**Comment by Tanzeel159** [comment] 2023-08-18 04:37
Oh interesting . Yeah I had privateDNS enabled. Thanks for clarifying .
