### ISSUE TITLE
bug: Root install does not work after a reboot

### ISSUE THREAD

**Issue by marcofugaro** [ReVanced/revanced-manager#519] opened 2022-11-16 13:38 UTC
### Type

Error at runtime

### Bug description

The root installation is succesful, but after a reboot, it gets reset and youtube crashes when opening.

### Steps to reproduce

1. Download [YouTube 17.43.36](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-43-36-release/youtube-17-43-36-2-android-apk-download/)
2. Extracy the `.apk`
3. Install the .apk via adb (`./adb install -r -d ./yt.apk`)
4. Open ReVanced Manager
5. Go to Patcher and select YouTube
6. Select the patches (listed below)
7. Click on Patch
8. Click on Install as Root
9. Click Open
10. ReVanced works normally
11. Make sure YouTube updates are turned off in the Play Store
<img src="https://user-images.githubusercontent.com/7217420/202187852-6170c167-c0c3-4259-bef7-e7f1f83850df.png" width="250" />

12. Reboot phone
13. A popup appears with "Your device isn't certified to run Google apps..."
14. ReVanced doesn't open anymore, it crashes on startup

### Android version

Android 13 on Pixel 7
5 October 2022 Security update

### Manager version

0.0.40

### Target package name

YouTube

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

<img src="https://user-images.githubusercontent.com/7217420/202192909-2ea735d0-555e-4885-a83c-023a2367a915.png" 
  width="350" />

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=0
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=1
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=2
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=3
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=4
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=5
11-16 14:26:35.738 13267 13267 E SurfaceSyncer: Failed to find sync for id=6
11-16 14:26:52.652 13346 13346 W sh      : type=1400 audit(0.0:7251): avc: denied { read } for name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-16 14:26:52.692 13346 13346 W sh      : type=1400 audit(0.0:7252): avc: denied { read } for name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-16 14:26:52.716 13346 13346 W sh      : type=1400 audit(0.0:7253): avc: denied { read } for name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-16 14:26:52.744 13346 13346 W sh      : type=1400 audit(0.0:7254): avc: denied { read } for name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-16 14:26:52.768 13346 13346 W sh      : type=1400 audit(0.0:7255): avc: denied { read } for name="/" dev="dm-12" ino=2 scontext=u:r:untrusted_app:s0:c2,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=0
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=1
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=2
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=3
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=4
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=5
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=6
11-16 14:29:06.265 13267 13267 E SurfaceSyncer: Failed to find sync for id=7
```

### Screenshots or videos

<img width="350" alt="image" src="https://user-images.githubusercontent.com/7217420/202194342-d5c15420-add8-448a-afc8-913cf8340c34.png">

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] #698
- [X] The issue is related solely to the ReVanced Manager

**Comment by deathline94** [comment] 2022-11-17 19:33
I second this ! i dont know what causes this but for me, going back to the 0.0.39 of the manager fixed it

**Comment by ibyb007** [comment] 2022-11-18 10:35
I've already reported this.. Check bug #497 I was surprised that no one facing this issue. Finally some1 reported this.

**Comment by oSumAtrIX** [comment] 2022-11-18 10:36
Downgrading as you described it is not possible on Android without uninstalling the app. Disable auto updates.

**Comment by bassmadrigal** [comment] 2022-11-26 07:43
I want to chime in with the same issue. I've always had auto updates disabled in Play Store and I've had this issue with every version of ReVanced YouTube I've installed, including the manually built versions with revanced-cli before ReVanced Manager was released. Vanced always survived reboots.

My app title always changes to something like "Pick theme to continue", but I'd need to reboot again to see it and give you the exact title.

The only way I've found to "fix" it is to clear the app's storage, "uninstall updates" in the Play Store (which just reverts me back to the original version included with my Android device without updates), and then repatch YouTube with ReVanced. This requires me to go through and adjust all my YouTube and ReVanced settings every reboot, which as you can imagine, is quite the hassle.

This is on a stock Pixel 7 rooted with Magisk with passing SafetyNet and occurred with my Pixel 6 as well. I wonder if it might just be an issue on Pixel devices...

**Comment by deathline94** [comment] 2022-11-26 10:05
@bassmadrigal  definitely not a pixel issue . i had it on an rooted Oneplus 8t and people have it on diffrent devices . i only managed to fix it by installing the 0.0.39 vesion of the manager app , set the SElinux to permissive and patching once again.
but still dont know the actual cause.

**Comment by ibyb007** [comment] 2022-11-29 16:45
> I can confirm, I too am facing the same issue. I tried patching with the remix script and the ReVanced patcher app as well, but facing the same issue on both installs. For me it does survive about one or two reboots, but post that or basically every 5 - 10 days, it starts this same behavior.
> 
> I am using lineage os 19.1 on Poco F1. I don't have YouTube installed as part of base google apps package. I either install it from play store or from apk as a user app. Once it breaks, updating to a newer version and patching doesn't work either.
> 
> This is what I see once it is broken. ![Screenshot_20221129-202006_Settings](https://user-images.githubusercontent.com/11255535/204561401-991965bb-958c-447a-8cc2-83253db81bbc.png)
> 
> After this my only option is to uninstall, reinstall the apk and patch it with root method again.

it's definitely a revanced manager issue.. I can still install vanced youtube without any issue.

**Comment by helpimnotdrowning** [comment] 2022-12-11 05:01
This was also happening to me, though I was getting app titles like "Auto translate", "{0} Chart", and "Are you sure?" (though this one was for YouTube Music). Sometime it can manage to survive a reboot, but it's very inconsistent and the app usually crashes on startup. I'm running Android 11 rooted on an LGv60.

(currently, I can't replicate it anymore due to being unable to patch anything-- blank screen on patches menu, and when it does work, some strange error messages appear, maybe permissions error?)

**Comment by marcofugaro** [comment] 2022-12-11 09:00
I can't patch youtube anymore, it alwaysaborts

**Comment by kenethc** [comment] 2023-01-10 02:53
> This was also happening to me, though I was getting app titles like "Auto translate", "{0} Chart", and "Are you sure?" (though this one was for YouTube Music). Sometime it can manage to survive a reboot, but it's very inconsistent and the app usually crashes on startup. I'm running Android 11 rooted on an LGv60.
> 
> (currently, I can't replicate it anymore due to being unable to patch anything-- blank screen on patches menu, and when it does work, some strange error messages appear, maybe permissions error?)

ReVanved Manager:
Clear cache
Clear data
open app

Un-patched the application in question (eg: YouTube) if the app shows as patched in ReVanved Manager. 

YouTube:
Clear cache
Clear data 
Uninstall all updates for YouTube - reset app back to factory if you know what I mean. 

Then update to required version by using apk from ApkMirror for example.

Don't open YouTube yet. 

ReVanced Manager:
Clear cache
Clear data

Open ReVanved Manager. 

Enable experimental support in settings

Check the list of patched applications and make sure YouTube is not showing. 

Patch Youtube and install - i installed as root. 

Then go ahead and open YouTube

**Comment by MulverineX** [comment] 2023-06-24 07:46
I am reproducing this issue on the Google Pixel 7 pro

**Comment by fr1sty** [comment] 2023-07-10 09:50
Finally I Fixed it by uninstalling Revanced Manager and deleting everything with Revanced mentioned here [https://github.com/revanced/revanced-manager/issues/425](https://github.com/revanced/revanced-manager/issues/425) . After that I could reboot and Youtube/Music wouldn't revert back. Now I'm using the Magisk module, seems to be working for now.

**Comment by TheTBO** [comment] 2023-08-03 13:36
For me, systemlessly removing the system YouTube and creating the post-data-fs.d and service.d directories fixed the issue

**Comment by ibyb007** [comment] 2023-08-03 13:41
I use magisk module of revanced by j-hc now.It doesn't have that bug + it's far more convenient to update.

**Comment by Ushie** [comment] 2023-08-05 17:55
Closing as its dupe of #425

**Closed by Ushie** 2023-08-05 17:55 UTC
Labels: bug
