### ISSUE TITLE
bug: 0.0.53 Fails to patch YouTube and aborts

### ISSUE THREAD

**Issue by 0o0will0o0** [revanced/revanced-manager#648] opened 2023-01-18 01:35 UTC
### Type

Error at runtime

### Bug description

Through patching recommend YouTube v17.49.37 with the latest updated manager app, the patching process fails with recommend patches, freezing on the aborting process. I attempted on two android 11 devices and they result the same.

### Steps to reproduce

Update manager to latest and attempt to patch YouTube.

### Android version

11

### Manager version

0.0.53

### Target package name

com.google.android.youtube

### Target package version.

17.49.37

### Installation type

Non-root

### Patches selected.

Recommend

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborting
Error:
java.lang.NoSuchMethodError: No static method isAndroid()Z in class Lbrut/util/OSDetection; or its super classes (declaration of 'brut.util.OSDetection' appears in base.apk)
	at brut.androlib.res.decoder.Res9patchStreamDecoder.<init>(Res9patchStreamDecoder.java:43)
	at brut.androlib.res.AndrolibResources.getResFileDecoder(AndrolibResources.java:693)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:221)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:225)
	at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:347)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by SammCheese** [comment] 2023-01-18 01:43
Can confirm

**Comment by Wykeless** [comment] 2023-01-18 02:09
happening for me too

**Comment by Freepony** [comment] 2023-01-18 02:34
Can confirm too, 0.52 works fine though.

**Comment by BadBoy-Github** [comment] 2023-01-18 02:41
happening for me too

**Comment by E85Addict** [comment] 2023-01-18 02:55
Not adding spam here like everyone else, but here's a log that the issue is also occurring in CLI

``
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging integrations-v0.93.1
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Deleting existing resource cache directory
INFO: Decoding resources
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean brut.util.OSDetection.isAndroid()'
        at brut.androlib.res.decoder.Res9patchStreamDecoder.<init>(Res9patchStreamDecoder.java:43)
        at brut.androlib.res.AndrolibResources.getResFileDecoder(AndrolibResources.java:693)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:221)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
        at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:225)
        at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:347)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
        ```

**Comment by SammCheese** [comment] 2023-01-18 08:07
Marking confirmations of an existing bug as spam is highly unprofessional.

**Comment by oSumAtrIX** [comment] 2023-01-18 08:14
Confirmations are not necessary nor required. It causes spam and does not contribute any useful information other than "me too".

**Comment by reisxd** [comment] 2023-01-18 08:14
> Marking confirmations of an existing bug as spam is highly unprofessional. 

Does it help though? No. Just saying "same for me!!" does not help and it's just spamming. And that's why it's marked as spam.

**Comment by SammCheese** [comment] 2023-01-18 08:20
It serves its purpose of isolating single-occurrence bugs from common and more severe bugs.
While there is the "thumbs up" reaction, it is not directly visible in the Issue list whereas comments are.
A higher number of comments could then indicate a more severe or urgent issue.

**Comment by oSumAtrIX** [comment] 2023-01-18 08:32
Severity is derrived from the original issue and usually we follow up with comments on issues if we need to confirm if its a single-occurence or not when necessary. In this instance the issue has already been confirmed on our end and it is unnecessary to write "me too" multiple times when it does not contribute more than the original issue.

**Comment by Ushie** [comment] 2023-01-22 14:17
Reinstall ReVanced Manager, it was re-released

**Closed by Ushie** 2023-01-22 14:17 UTC
Labels: bug
