### ISSUE TITLE
feat: Apk Download

### ISSUE THREAD

**Issue by ibrahimashraf** [revanced/revanced-manager#508] opened 2022-11-13 21:14 UTC
### Type

Functionality

### Issue

can you please enable downloading the suitable apk for the the latest patches?
as the app only patching installed apks while mine are newer and cannot downgrade to older version. 
instead of adding a warning that these patches only support these versions, add an option to download these versions it self

### Feature

can you please enable downloading the suitable apk for the the latest patches?
as the app only patching installed apks while mine are newer and cannot downgrade to older version. 
instead of adding a warning that these patches only support these versions, add an option to download these versions it self

### Motivation

can you please enable downloading the suitable apk for the the latest patches?
as the app only patching installed apks while mine are newer and cannot downgrade to older version. 
instead of adding a warning that these patches only support these versions, add an option to download these versions it self

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment] 2022-11-13 21:21
Dupe of #436, #125, #12

**Closed by Ushie** 2022-11-13 21:21 UTC
Labels: feature-request
