### ISSUE TITLE
bug: Cannot patch YouTube

### ISSUE THREAD

**Issue by pradeethd** [ReVanced/revanced-manager#1037] opened 2023-07-18 02:26 UTC
### Type

Error while running the manager

### Bug description

I tried to patch YouTube v18.23.35 using the manager v1.4.1. I got the following errors provided in the screenshot below. I also tried with both bundle apks and no-dpi apk file installed. Also with previous manager version. But still got the same errors. 

### Steps to reproduce

Device: Redmi Note 10 (mojito)
OS: Android 13 - Pixel OS 
Rooted: Yes (magisk)
Latest Google Play Services used.
YouTube v18.23.35 used.
Revanced Manager v1.4.1 used.

### Android version

13

### Manager version

1.4.1

### Target package name

YouTube

### Target package version.

18.23.35

### Installation type

Root

### Patches selected.

Selected patches (19)
Copy Video Url (v0.0.1)
Disable Shorts Orn Startup (v0.0.1) External Downloads (v0.0.1)
Hdr Auto Brightness (v0.0.2)
Hide Ads (v0.0.1)
Hide Crowdfunding Box (v0.0.1)
Hide Watermark (v0.0.1)
Minimized Playback (v0.0.1)
Open Links Externally (v0.0.1)
Premium Heading (v0.0.1)
Remember Video Quality (v0.0.1) Return Youtube Dislike (v0.0.1) •Seekbar Tapping (v0.0.1)
Sponsorblock (v0.0.1)
Swipe Controls (v0.0.3)
Theme (v0.0.1)
Video Ads (v0.0.1)
Video Speed (v0.0.1)
Custom Video Buffer (v0.0.1)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
07-18 07:54:01.803 14473 14490 E OpenGLRenderer: Unable to match the desired swap behavior.
07-18 07:54:01.864 14473 14473 E SurfaceSyncer: Failed to find sync for id=0
07-18 07:54:01.864 14473 14473 E SurfaceSyncer: Failed to find sync for id=1
07-18 07:54:25.984 14473 14490 E OpenGLRenderer: Unable to match the desired swap behavior.
07-18 07:54:25.987 14473 14473 E SurfaceSyncer: Failed to find sync for id=0
07-18 07:54:25.987 14473 14473 E SurfaceSyncer: Failed to find sync for id=1
07-18 07:54:25.987 14473 14473 E SurfaceSyncer: Failed to find sync for id=2
07-18 07:55:02.115 14473 14473 E BLASTBufferQueue: [VRI[MainActivity]#4](f:0,a:1) Applying pending transactions on dtor 1
07-18 07:55:21.861 14473 14490 E OpenGLRenderer: Unable to match the desired swap behavior.
07-18 07:55:21.867 14473 14473 E SurfaceSyncer: Failed to find sync for id=0
07-18 07:55:21.867 14473 14473 E SurfaceSyncer: Failed to find sync for id=1
07-18 07:55:21.867 14473 14473 E SurfaceSyncer: Failed to find sync for id=2
07-18 07:55:21.867 14473 14473 E SurfaceSyncer: Failed to find sync for id=3
07-18 07:55:24.722 14473 14473 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10278; state: ENABLED
```

### Screenshots or video

![Screenshot_20230717-184651](https://github.com/ReVanced/revanced-manager/assets/69318228/90ee267f-e191-446b-8016-02766d85fb10)

### Acknowledgments

- [ ] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment] 2023-07-18 07:21
Duplicate of #975

**Closed by TheAabedKhan** 2023-07-18 07:21 UTC
Labels: bug
